### 读取Oregano数据

In [1]:
import math
import os

In [2]:
import gravis as gv  # for visualization of the KG schema and subgraphs, developed by the author of this notebook
import igraph as ig
import pandas as pd

In [3]:
import shared_bmkg

In [4]:
project_name = "oregano"
download_dir = os.path.join(project_name, "downloads")
results_dir = os.path.join(project_name, "results")

In [5]:
download_specification = [
    ("OREGANO_V2.1.tsv", "https://figshare.com/ndownloader/files/42612700", "3e534cadf7717c705cbd5e6dd8c392a6"),

    ("ACTIVITY.tsv", "https://figshare.com/ndownloader/files/42612697", "d1faec938bd32ec9bb45ae5bba14d7a2"),
    ("COMPOUND.tsv", "https://figshare.com/ndownloader/files/42612676", "d86277d0e849c3774acb3c6be1878b44"),
    ("DISEASES.tsv", "https://figshare.com/ndownloader/files/42612685", "747a48c9786fd50912bb8d7f33d630df"),
    ("EFFECT.tsv", "https://figshare.com/ndownloader/files/42612694", "9b1656a45df7d0369dc2a8e5f52b5c2b"),
    ("GENES.tsv", "https://figshare.com/ndownloader/files/42612673", "8fe9a917b23ab715a268feda50b4a8d7"),
    ("INDICATION.tsv", "https://figshare.com/ndownloader/files/42612691", "eae2cbaebc64b1387cce1755a386d1cb"),
    ("PATHWAYS.tsv", "https://figshare.com/ndownloader/files/42612688", "d3f0abefe355c4b9cd1eea4cc8d58021"),
    ("PHENOTYPES.tsv", "https://figshare.com/ndownloader/files/42612679", "cada3e9316ba4ec654dd2b9ec2afa23c"),
    ("SIDE_EFFECT.tsv", "https://figshare.com/ndownloader/files/42612670", "8388b5a37db250128e50571d42d96cbc"),
    ("TARGET.tsv", "https://figshare.com/ndownloader/files/42612682", "46e189c556b2b010952d4212b8779cef"),

    ("oreganov2.1_metadata_complete.ttl", "https://figshare.com/ndownloader/files/42700234", "b087300f5e597d263a03c02eaae53bc7"),
]

In [6]:
df_kg = shared_bmkg.read_tsv_file(os.path.join(download_dir, "OREGANO_V2.1.tsv"), header=None)
df_kg.columns = ["subject", "predicate", "object"]

In [7]:
df_kg.tail()

              subject        predicate      object
823000  PROTEIN:22090  gene_product_of  GENE:32165
823001  PROTEIN:22091  gene_product_of  GENE:33606
823002  PROTEIN:22093  gene_product_of  GENE:35418
823003  PROTEIN:22095  gene_product_of  GENE:31330
823004  PROTEIN:22096  gene_product_of  GENE:25313

In [8]:
df_activity = shared_bmkg.read_tsv_file(os.path.join(download_dir, "ACTIVITY.tsv"))
df_activity.columns.values[0] = "id"

df_compound = shared_bmkg.read_tsv_file(os.path.join(download_dir, "COMPOUND.tsv"))
df_compound.columns.values[0] = "id"

df_diseases = shared_bmkg.read_tsv_file(os.path.join(download_dir, "DISEASES.tsv"))
df_diseases.columns.values[0] = "id"

df_effect = shared_bmkg.read_tsv_file(os.path.join(download_dir, "EFFECT.tsv"))
df_effect.columns.values[0] = "id"

df_genes = shared_bmkg.read_tsv_file(os.path.join(download_dir, "GENES.tsv"))
df_genes.columns.values[0] = "id"

df_indication = shared_bmkg.read_tsv_file(os.path.join(download_dir, "INDICATION.tsv"))
df_indication.columns.values[0] = "id"

df_pathways = shared_bmkg.read_tsv_file(os.path.join(download_dir, "PATHWAYS.tsv"))
df_pathways.columns.values[0] = "id"

df_phenotypes = shared_bmkg.read_tsv_file(os.path.join(download_dir, "PHENOTYPES.tsv"))
df_phenotypes.columns.values[0] = "id"

df_sideeffect = shared_bmkg.read_tsv_file(os.path.join(download_dir, "SIDE_EFFECT.tsv"))
df_sideeffect.columns.values[0] = "id"

df_target = shared_bmkg.read_tsv_file(os.path.join(download_dir, "TARGET.tsv"))
df_target.columns.values[0] = "id"

In [9]:
# rdf_kg = shared_bmkg.read_ttl_file(os.path.join(download_dir, "oreganov2.1_metadata_complete.ttl"))

### Attempt to identify the possible causes of a disease (e.g., genes, proteins, etc.)

A disease ID corresponds to different names across various databases.

In [10]:
df_diseases.columns

Index(['id', 'PHARMGKB', 'MESH', ' SNOMEDCT', ' UMLS', ' NDFRT', ' MEDDRA',
       'SNOMEDCT', 'NDFRT', ' MESH', 'MEDDRA', 'UMLS', 'ORPHANET', 'ICD-11',
       'ICD-10', 'OMIM', 'GARD'],
      dtype='object')

In [11]:
print(len(df_diseases))
df_diseases.head()

18333

,id,PHARMGKB,MESH,SNOMEDCT,UMLS,NDFRT,MEDDRA,SNOMEDCT,NDFRT,MESH,MEDDRA,UMLS,ORPHANET,ICD-11,ICD-10,OMIM,GARD
0,DISEASE:1,PA165108557,D054868,4325000,C0795841,N0000181176,NaN,NaN,NaN,NaN,NaN,C0795841,2308,LD44.B0,Q93.5,NaN,307
1,DISEASE:2,PA446766,D018784,75100008,C0243001,N0000003856,10060921,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,DISEASE:3,PA165109087,D018221,400153009,C0206646,N0000003695,10059354,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,DISEASE:4,PA446220,D015746,207205003;21522001,C0000737,N0000003309,10000039,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,DISEASE:5,PA165109033,D020434,398963001,C0271355,N0000004148,10053662,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df_disease_valid = df_diseases[['id', 'ICD-10']][df_diseases['ICD-10'].notna()]

In [13]:
print(len(df_disease_valid))
df_disease_valid.head()

7617

            id         ICD-10
0    DISEASE:1          Q93.5
5    DISEASE:6          E78.6
15  DISEASE:16  B60.1+;H19.2*
22  DISEASE:23          Q77.4
33  DISEASE:34          F80.3

In [14]:
disease1 = df_disease_valid.iloc[0]['id']
print(disease1)

DISEASE:1

In [15]:
df_kg.head()

      subject predicate   object
0  COMPOUND:1  has_code  B01AE02
1  COMPOUND:2  has_code  L01FE01
2  COMPOUND:3  has_code  R05CB13
3  COMPOUND:4  has_code  L01XX29
4  COMPOUND:5  has_code  L04AB01

In [16]:
disease_gene = df_kg[df_kg["predicate"]=="causes_condition"]
disease_gene = disease_gene[disease_gene["object"].isin(df_disease_valid["id"])]
print("num:", len(disease_gene))
disease_gene.head()

num: 5977

           subject         predicate        object
346840  GENE:26358  causes_condition  DISEASE:7531
346844  GENE:26563  causes_condition  DISEASE:7148
346845  GENE:26633  causes_condition  DISEASE:3120
346849  GENE:26949  causes_condition  DISEASE:5893
346857  GENE:29026  causes_condition  DISEASE:7140

In [17]:
disease_gene[disease_gene["object"] == disease1]

           subject         predicate     object
352958  GENE:27214  causes_condition  DISEASE:1

In [18]:
gene_protein = df_kg[df_kg["predicate"]=="gene_product_of"]
gene_protein = gene_protein[gene_protein["object"].isin(disease_gene["subject"])]
print("num:", len(gene_protein))
gene_protein.head()

num: 2576

             subject        predicate      object
812125  PROTEIN:6194  gene_product_of  GENE:33567
812129  PROTEIN:6882  gene_product_of  GENE:27501
812130  PROTEIN:6883  gene_product_of  GENE:27378
812132  PROTEIN:6885  gene_product_of  GENE:24846
812139  PROTEIN:4328  gene_product_of  GENE:33274

A disease is caused by a specific gene, and this gene produces certain proteins. Therefore, the disease is caused by these proteins.

Given a disease, it should be possible to infer its associated proteins.

In [19]:
def abductive_reasoning(disease_id, disease_gene, gene_protein):
    genes_proteins = []
    df_genes = disease_gene[disease_gene["object"] == disease_id]
    if len(df_genes) == 0:
        return genes_proteins
    for gene in df_genes["subject"]:
        df_proteins = gene_protein[gene_protein["object"] == gene]
        if len(df_proteins) == 0:
            continue
        genes_proteins.append((gene, list(df_proteins["subject"])))
    return genes_proteins

ICD-10 to ICD-9
https://www.nber.org/research/data/icd-9-cm-and-icd-10-cm-and-icd-10-pcs-crosswalk-or-general-equivalence-mappings

In [20]:
icd_mapping = pd.read_csv("icd10cmtoicd9gem.csv")
icd_mapping = icd_mapping[['icd10cm', 'icd9cm']]
icd_mapping.set_index('icd10cm', inplace=True)
icd_mapping = icd_mapping['icd9cm'].to_dict()

In [21]:
str(df_disease_valid['ICD-10'].iloc[0]).replace('.', '') in icd_mapping

True

In [22]:
df_disease_valid

                  id         ICD-10
0          DISEASE:1          Q93.5
5          DISEASE:6          E78.6
15        DISEASE:16  B60.1+;H19.2*
22        DISEASE:23          Q77.4
33        DISEASE:34          F80.3
...              ...            ...
13700  DISEASE:13701          E72.1
13701  DISEASE:13702          D81.8
13705  DISEASE:13706          D76.1
13706  DISEASE:13707          D56.4
13707  DISEASE:13708          Q87.8

[7617 rows x 2 columns]

In [23]:
for k in icd_mapping.keys():
    print(k)

A000
A001
A009
A0100
A0101
A0102
A0103
A0104
A0105
A0109
A011
A012
A013
A014
A020
A021
A0220
A0221
A0222
A0223
A0224
A0225
A0229
A028
A029
A030
A031
A032
A033
A038
A039
A040
A041
A042
A043
A044
A045
A046
A047
A048
A049
A050
A051
A052
A053
A054
A055
A058
A059
A060
A061
A062
A063
A064
A065
A066
A067
A0681
A0682
A0689
A069
A070
A071
A072
A073
A074
A078
A079
A080
A0811
A0819
A082
A0831
A0832
A0839
A084
A088
A09
A150
A154
A155
A156
A157
A158
A159
A170
A171
A1781
A1782
A1783
A1789
A179
A1801
A1802
A1803
A1809
A1810
A1811
A1812
A1813
A1814
A1815
A1816
A1817
A1818
A182
A1831
A1832
A1839
A184
A1850
A1851
A1852
A1853
A1854
A1859
A186
A187
A1881
A1882
A1883
A1884
A1885
A1889
A190
A191
A192
A198
A199
A200
A201
A202
A203
A207
A208
A209
A210
A211
A212
A213
A217
A218
A219
A220
A221
A222
A227
A228
A229
A230
A231
A232
A233
A238
A239
A240
A241
A242
A243
A249
A250
A251
A259
A260
A267
A268
A269
A270
A2781
A2789
A279
A280
A281
A282
A288
A289
A300
A301
A302
A303
A304
A305
A308
A309
A310
A311
A312
A318
A319
A320
A3211
A3212
A327
A3281
A3282
A3289
A329
A33
A34
A35
A360
A361
A362
A363
A3681
A3682
A3683
A3684
A3685
A3686
A3689
A369
A3700
A3701
A3710
A3711
A3780
A3781
A3790
A3791
A380
A381
A388
A389
A390
A391
A392
A393
A394
A3950
A3951
A3952
A3953
A3981
A3982
A3983
A3984
A3989
A399
A400
A401
A403
A408
A409
A4101
A4102
A411
A412
A413
A414
A4150
A4151
A4152
A4153
A4159
A4181
A4189
A419
A420
A421
A422
A427
A4281
A4282
A4289
A429
A430
A431
A438
A439
A440
A441
A448
A449
A46
A480
A481
A482
A483
A484
A4851
A4852
A488
A4901
A4902
A491
A492
A493
A498
A499
A5001
A5002
A5003
A5004
A5005
A5006
A5007
A5008
A5009
A501
A502
A5030
A5031
A5032
A5039
A5040
A5041
A5042
A5043
A5044
A5045
A5049
A5051
A5052
A5053
A5054
A5055
A5056
A5057
A5059
A506
A507
A509
A510
A511
A512
A5131
A5132
A5139
A5141
A5142
A5143
A5144
A5145
A5146
A5149
A515
A519
A5200
A5201
A5202
A5203
A5204
A5205
A5206
A5209
A5210
A5211
A5212
A5213
A5214
A5215
A5216
A5217
A5219
A522
A523
A5271
A5272
A5273
A5274
A5275
A5276
A5277
A5278
A5279
A528
A529
A530
A539
A5400
A5401
A5402
A5403
A5409
A541
A5421
A5422
A5423
A5424
A5429
A5430
A5431
A5432
A5433
A5439
A5440
A5441
A5442
A5443
A5449
A545
A546
A5481
A5482
A5483
A5484
A5485
A5486
A5489
A549
A55
A5600
A5601
A5602
A5609
A5611
A5619
A562
A563
A564
A568
A57
A58
A5900
A5901
A5902
A5903
A5909
A598
A599
A6000
A6001
A6002
A6003
A6004
A6009
A601
A609
A630
A638
A64
A65
A660
A661
A662
A663
A664
A665
A666
A667
A668
A669
A670
A671
A672
A673
A679
A680
A681
A689
A690
A691
A6920
A6921
A6922
A6923
A6929
A698
A699
A70
A710
A711
A719
A740
A7481
A7489
A749
A750
A751
A752
A753
A759
A770
A771
A772
A773
A7740
A7741
A7749
A778
A779
A78
A790
A791
A7981
A7989
A799
A800
A801
A802
A8030
A8039
A804
A809
A8100
A8101
A8109
A811
A812
A8181
A8182
A8183
A8189
A819
A820
A821
A829
A830
A831
A832
A833
A834
A835
A836
A838
A839
A840
A841
A848
A849
A850
A851
A852
A858
A86
A870
A871
A872
A878
A879
A880
A881
A888
A89
A90
A91
A920
A921
A922
A9230
A9231
A9232
A9239
A924
A928
A929
A930
A931
A932
A938
A94
A950
A951
A959
A960
A961
A962
A968
A969
A980
A981
A982
A983
A984
A985
A988
A99
B000
B001
B002
B003
B004
B0050
B0051
B0052
B0053
B0059
B007
B0081
B0082
B0089
B009
B010
B0111
B0112
B012
B0181
B0189
B019
B020
B021
B0221
B0222
B0223
B0224
B0229
B0230
B0231
B0232
B0233
B0234
B0239
B027
B028
B029
B03
B04
B050
B051
B052
B053
B054
B0581
B0589
B059
B0600
B0601
B0602
B0609
B0681
B0682
B0689
B069
B070
B078
B079
B08010
B08011
B0802
B0803
B0804
B0809
B081
B0820
B0821
B0822
B083
B084
B085
B0860
B0861
B0862
B0869
B0870
B0871
B0872
B0879
B088
B09
B1001
B1009
B1081
B1082
B1089
B150
B159
B160
B161
B162
B169
B170
B1710
B1711
B172
B178
B179
B180
B181
B182
B188
B189
B190
B1910
B1911
B1920
B1921
B199
B20
B250
B251
B252
B258
B259
B260
B261
B262
B263
B2681
B2682
B2683
B2684
B2685
B2689
B269
B2700
B2701
B2702
B2709
B2710
B2711
B2712
B2719
B2780
B2781
B2782
B2789
B2790
B2791
B2792
B2799
B300
B301
B302
B303
B308
B309
B330
B331
B3320
B3321
B3322
B3323
B3324
B333
B334
B338
B340
B341
B342
B343
B344
B348
B349
B350
B351
B352
B353
B354
B355
B356
B358
B359
B360
B361
B362
B363
B368
B369
B370
B371
B372
B373
B3741
B3742
B3749
B375
B376
B377
B3781
B3782
B3783
B3784
B3789
B379
B380
B381
B382
B383
B384
B387
B3881
B3889
B389
B390
B391
B392
B393
B394
B395
B399
B400
B401
B402
B403
B407
B4081
B4089
B409
B410
B417
B418
B419
B420
B421
B427
B4281
B4282
B4289
B429
B430
B431
B432
B438
B439
B440
B441
B442
B447
B4481
B4489
B449
B450
B451
B452
B453
B457
B458
B459
B460
B461
B462
B463
B464
B465
B468
B469
B470
B471
B479
B480
B481
B482
B483
B484
B488
B49
B500
B508
B509
B510
B518
B519
B520
B528
B529
B530
B531
B538
B54
B550
B551
B552
B559
B560
B561
B569
B570
B571
B572
B5730
B5731
B5732
B5739
B5740
B5741
B5742
B5749
B575
B5800
B5801
B5809
B581
B582
B583
B5881
B5882
B5883
B5889
B589
B59
B600
B6010
B6011
B6012
B6013
B6019
B602
B608
B64
B650
B651
B652
B653
B658
B659
B660
B661
B662
B663
B664
B665
B668
B669
B670
B671
B672
B6731
B6732
B6739
B674
B675
B6761
B6769
B677
B678
B6790
B6799
B680
B681
B689
B690
B691
B6981
B6989
B699
B700
B701
B710
B711
B718
B719
B72
B7300
B7301
B7302
B7309
B731
B740
B741
B742
B743
B744
B748
B749
B75
B760
B761
B768
B769
B770
B7781
B7789
B779
B780
B781
B787
B789
B79
B80
B810
B811
B812
B813
B814
B818
B820
B829
B830
B831
B832
B833
B834
B838
B839
B850
B851
B852
B853
B854
B86
B870
B871
B872
B873
B874
B8781
B8782
B8789
B879
B880
B881
B882
B883
B888
B889
B89
B900
B901
B902
B908
B909
B91
B92
B940
B941
B942
B948
B949
B950
B951
B952
B953
B954
B955
B9561
B9562
B957
B958
B960
B961
B9620
B9621
B9622
B9623
B9629
B963
B964
B965
B966
B967
B9681
B9682
B9689
B970
B9710
B9711
B9712
B9719
B9721
B9729
B9730
B9731
B9732
B9733
B9734
B9735
B9739
B974
B975
B976
B977
B9781
B9789
B998
B999
C000
C001
C002
C003
C004
C005
C006
C008
C009
C01
C020
C021
C022
C023
C024
C028
C029
C030
C031
C039
C040
C041
C048
C049
C050
C051
C052
C058
C059
C060
C061
C062
C0680
C0689
C069
C07
C080
C081
C089
C090
C091
C098
C099
C100
C101
C102
C103
C104
C108
C109
C110
C111
C112
C113
C118
C119
C12
C130
C131
C132
C138
C139
C140
C142
C148
C153
C154
C155
C158
C159
C160
C161
C162
C163
C164
C165
C166
C168
C169
C170
C171
C172
C173
C178
C179
C180
C181
C182
C183
C184
C185
C186
C187
C188
C189
C19
C20
C210
C211
C212
C218
C220
C221
C222
C223
C224
C227
C228
C229
C23
C240
C241
C248
C249
C250
C251
C252
C253
C254
C257
C258
C259
C260
C261
C269
C300
C301
C310
C311
C312
C313
C318
C319
C320
C321
C322
C323
C328
C329
C33
C3400
C3401
C3402
C3410
C3411
C3412
C342
C3430
C3431
C3432
C3480
C3481
C3482
C3490
C3491
C3492
C37
C380
C381
C382
C383
C384
C388
C390
C399
C4000
C4001
C4002
C4010
C4011
C4012
C4020
C4021
C4022
C4030
C4031
C4032
C4080
C4081
C4082
C4090
C4091
C4092
C410
C411
C412
C413
C414
C419
C430
C4310
C4311
C4312
C4320
C4321
C4322
C4330
C4331
C4339
C434
C4351
C4352
C4359
C4360
C4361
C4362
C4370
C4371
C4372
C438
C439
C4400
C4401
C4402
C4409
C44101
C44102
C44109
C44111
C44112
C44119
C44121
C44122
C44129
C44191
C44192
C44199
C44201
C44202
C44209
C44211
C44212
C44219
C44221
C44222
C44229
C44291
C44292
C44299
C44300
C44301
C44309
C44310
C44311
C44319
C44320
C44321
C44329
C44390
C44391
C44399
C4440
C4441
C4442
C4449
C44500
C44501
C44509
C44510
C44511
C44519
C44520
C44521
C44529
C44590
C44591
C44599
C44601
C44602
C44609
C44611
C44612
C44619
C44621
C44622
C44629
C44691
C44692
C44699
C44701
C44702
C44709
C44711
C44712
C44719
C44721
C44722
C44729
C44791
C44792
C44799
C4480
C4481
C4482
C4489
C4490
C4491
C4492
C4499
C450
C451
C452
C457
C459
C460
C461
C462
C463
C464
C4650
C4651
C4652
C467
C469
C470
C4710
C4711
C4712
C4720
C4721
C4722
C473
C474
C475
C476
C478
C479
C480
C481
C482
C488
C490
C4910
C4911
C4912
C4920
C4921
C4922
C493
C494
C495
C496
C498
C499
C4A0
C4A10
C4A11
C4A12
C4A20
C4A21
C4A22
C4A30
C4A31
C4A39
C4A4
C4A51
C4A52
C4A59
C4A60
C4A61
C4A62
C4A70
C4A71
C4A72
C4A8
C4A9
C50011
C50012
C50019
C50021
C50022
C50029
C50111
C50112
C50119
C50121
C50122
C50129
C50211
C50212
C50219
C50221
C50222
C50229
C50311
C50312
C50319
C50321
C50322
C50329
C50411
C50412
C50419
C50421
C50422
C50429
C50511
C50512
C50519
C50521
C50522
C50529
C50611
C50612
C50619
C50621
C50622
C50629
C50811
C50812
C50819
C50821
C50822
C50829
C50911
C50912
C50919
C50921
C50922
C50929
C510
C511
C512
C518
C519
C52
C530
C531
C538
C539
C540
C541
C542
C543
C548
C549
C55
C561
C562
C569
C5700
C5701
C5702
C5710
C5711
C5712
C5720
C5721
C5722
C573
C574
C577
C578
C579
C58
C600
C601
C602
C608
C609
C61
C6200
C6201
C6202
C6210
C6211
C6212
C6290
C6291
C6292
C6300
C6301
C6302
C6310
C6311
C6312
C632
C637
C638
C639
C641
C642
C649
C651
C652
C659
C661
C662
C669
C670
C671
C672
C673
C674
C675
C676
C677
C678
C679
C680
C681
C688
C689
C6900
C6901
C6902
C6910
C6911
C6912
C6920
C6921
C6922
C6930
C6931
C6932
C6940
C6941
C6942
C6950
C6951
C6952
C6960
C6961
C6962
C6980
C6981
C6982
C6990
C6991
C6992
C700
C701
C709
C710
C711
C712
C713
C714
C715
C716
C717
C718
C719
C720
C721
C7220
C7221
C7222
C7230
C7231
C7232
C7240
C7241
C7242
C7250
C7259
C729
C73
C7400
C7401
C7402
C7410
C7411
C7412
C7490
C7491
C7492
C750
C751
C752
C753
C754
C755
C758
C759
C760
C761
C762
C763
C7640
C7641
C7642
C7650
C7651
C7652
C768
C770
C771
C772
C773
C774
C775
C778
C779
C7800
C7801
C7802
C781
C782
C7830
C7839
C784
C785
C786
C787
C7880
C7889
C7900
C7901
C7902
C7910
C7911
C7919
C792
C7931
C7932
C7940
C7949
C7951
C7952
C7960
C7961
C7962
C7970
C7971
C7972
C7981
C7982
C7989
C799
C7A00
C7A010
C7A011
C7A012
C7A019
C7A020
C7A021
C7A022
C7A023
C7A024
C7A025
C7A026
C7A029
C7A090
C7A091
C7A092
C7A093
C7A094
C7A095
C7A096
C7A098
C7A1
C7A8
C7B00
C7B01
C7B02
C7B03
C7B04
C7B09
C7B1
C7B8
C800
C801
C802
C8100
C8101
C8102
C8103
C8104
C8105
C8106
C8107
C8108
C8109
C8110
C8111
C8112
C8113
C8114
C8115
C8116
C8117
C8118
C8119
C8120
C8121
C8122
C8123
C8124
C8125
C8126
C8127
C8128
C8129
C8130
C8131
C8132
C8133
C8134
C8135
C8136
C8137
C8138
C8139
C8140
C8141
C8142
C8143
C8144
C8145
C8146
C8147
C8148
C8149
C8170
C8171
C8172
C8173
C8174
C8175
C8176
C8177
C8178
C8179
C8190
C8191
C8192
C8193
C8194
C8195
C8196
C8197
C8198
C8199
C8200
C8201
C8202
C8203
C8204
C8205
C8206
C8207
C8208
C8209
C8210
C8211
C8212
C8213
C8214
C8215
C8216
C8217
C8218
C8219
C8220
C8221
C8222
C8223
C8224
C8225
C8226
C8227
C8228
C8229
C8230
C8231
C8232
C8233
C8234
C8235
C8236
C8237
C8238
C8239
C8240
C8241
C8242
C8243
C8244
C8245
C8246
C8247
C8248
C8249
C8250
C8251
C8252
C8253
C8254
C8255
C8256
C8257
C8258
C8259
C8260
C8261
C8262
C8263
C8264
C8265
C8266
C8267
C8268
C8269
C8280
C8281
C8282
C8283
C8284
C8285
C8286
C8287
C8288
C8289
C8290
C8291
C8292
C8293
C8294
C8295
C8296
C8297
C8298
C8299
C8300
C8301
C8302
C8303
C8304
C8305
C8306
C8307
C8308
C8309
C8310
C8311
C8312
C8313
C8314
C8315
C8316
C8317
C8318
C8319
C8330
C8331
C8332
C8333
C8334
C8335
C8336
C8337
C8338
C8339
C8350
C8351
C8352
C8353
C8354
C8355
C8356
C8357
C8358
C8359
C8370
C8371
C8372
C8373
C8374
C8375
C8376
C8377
C8378
C8379
C8380
C8381
C8382
C8383
C8384
C8385
C8386
C8387
C8388
C8389
C8390
C8391
C8392
C8393
C8394
C8395
C8396
C8397
C8398
C8399
C8400
C8401
C8402
C8403
C8404
C8405
C8406
C8407
C8408
C8409
C8410
C8411
C8412
C8413
C8414
C8415
C8416
C8417
C8418
C8419
C8440
C8441
C8442
C8443
C8444
C8445
C8446
C8447
C8448
C8449
C8460
C8461
C8462
C8463
C8464
C8465
C8466
C8467
C8468
C8469
C8470
C8471
C8472
C8473
C8474
C8475
C8476
C8477
C8478
C8479
C8490
C8491
C8492
C8493
C8494
C8495
C8496
C8497
C8498
C8499
C84A0
C84A1
C84A2
C84A3
C84A4
C84A5
C84A6
C84A7
C84A8
C84A9
C84Z0
C84Z1
C84Z2
C84Z3
C84Z4
C84Z5
C84Z6
C84Z7
C84Z8
C84Z9
C8510
C8511
C8512
C8513
C8514
C8515
C8516
C8517
C8518
C8519
C8520
C8521
C8522
C8523
C8524
C8525
C8526
C8527
C8528
C8529
C8580
C8581
C8582
C8583
C8584
C8585
C8586
C8587
C8588
C8589
C8590
C8591
C8592
C8593
C8594
C8595
C8596
C8597
C8598
C8599
C860
C861
C862
C863
C864
C865
C866
C880
C882
C883
C884
C888
C889
C9000
C9001
C9002
C9010
C9011
C9012
C9020
C9021
C9022
C9030
C9031
C9032
C9100
C9101
C9102
C9110
C9111
C9112
C9130
C9131
C9132
C9140
C9141
C9142
C9150
C9151
C9152
C9160
C9161
C9162
C9190
C9191
C9192
C91A0
C91A1
C91A2
C91Z0
C91Z1
C91Z2
C9200
C9201
C9202
C9210
C9211
C9212
C9220
C9221
C9222
C9230
C9231
C9232
C9240
C9241
C9242
C9250
C9251
C9252
C9260
C9261
C9262
C9290
C9291
C9292
C92A0
C92A1
C92A2
C92Z0
C92Z1
C92Z2
C9300
C9301
C9302
C9310
C9311
C9312
C9330
C9331
C9332
C9390
C9391
C9392
C93Z0
C93Z1
C93Z2
C9400
C9401
C9402
C9420
C9421
C9422
C9430
C9431
C9432
C9440
C9441
C9442
C946
C9480
C9481
C9482
C9500
C9501
C9502
C9510
C9511
C9512
C9590
C9591
C9592
C960
C962
C964
C965
C966
C969
C96A
C96Z
D0000
D0001
D0002
D0003
D0004
D0005
D0006
D0007
D0008
D001
D002
D010
D011
D012
D013
D0140
D0149
D015
D017
D019
D020
D021
D0220
D0221
D0222
D023
D024
D030
D0310
D0311
D0312
D0320
D0321
D0322
D0330
D0339
D034
D0351
D0352
D0359
D0360
D0361
D0362
D0370
D0371
D0372
D038
D039
D040
D0410
D0411
D0412
D0420
D0421
D0422
D0430
D0439
D044
D045
D0460
D0461
D0462
D0470
D0471
D0472
D048
D049
D0500
D0501
D0502
D0510
D0511
D0512
D0580
D0581
D0582
D0590
D0591
D0592
D060
D061
D067
D069
D070
D071
D072
D0730
D0739
D074
D075
D0760
D0761
D0769
D090
D0910
D0919
D0920
D0921
D0922
D093
D098
D099
D100
D101
D102
D1030
D1039
D104
D105
D106
D107
D109
D110
D117
D119
D120
D121
D122
D123
D124
D125
D126
D127
D128
D129
D130
D131
D132
D1330
D1339
D134
D135
D136
D137
D139
D140
D141
D142
D1430
D1431
D1432
D144
D150
D151
D152
D157
D159
D1600
D1601
D1602
D1610
D1611
D1612
D1620
D1621
D1622
D1630
D1631
D1632
D164
D165
D166
D167
D168
D169
D170
D171
D1720
D1721
D1722
D1723
D1724
D1730
D1739
D174
D175
D176
D1771
D1772
D1779
D179
D1800
D1801
D1802
D1803
D1809
D181
D190
D191
D197
D199
D200
D201
D210
D2110
D2111
D2112
D2120
D2121
D2122
D213
D214
D215
D216
D219
D220
D2210
D2211
D2212
D2220
D2221
D2222
D2230
D2239
D224
D225
D2260
D2261
D2262
D2270
D2271
D2272
D229
D230
D2310
D2311
D2312
D2320
D2321
D2322
D2330
D2339
D234
D235
D2360
D2361
D2362
D2370
D2371
D2372
D239
D241
D242
D249
D250
D251
D252
D259
D260
D261
D267
D269
D270
D271
D279
D280
D281
D282
D287
D289
D290
D291
D2920
D2921
D2922
D2930
D2931
D2932
D294
D298
D299
D3000
D3001
D3002
D3010
D3011
D3012
D3020
D3021
D3022
D303
D304
D308
D309
D3100
D3101
D3102
D3110
D3111
D3112
D3120
D3121
D3122
D3130
D3131
D3132
D3140
D3141
D3142
D3150
D3151
D3152
D3160
D3161
D3162
D3190
D3191
D3192
D320
D321
D329
D330
D331
D332
D333
D334
D337
D339
D34
D3500
D3501
D3502
D351
D352
D353
D354
D355
D356
D357
D359
D360
D3610
D3611
D3612
D3613
D3614
D3615
D3616
D3617
D367
D369
D3701
D3702
D37030
D37031
D37032
D37039
D3704
D3705
D3709
D371
D372
D373
D374
D375
D376
D378
D379
D380
D381
D382
D383
D384
D385
D386
D390
D3910
D3911
D3912
D392
D398
D399
D3A00
D3A010
D3A011
D3A012
D3A019
D3A020
D3A021
D3A022
D3A023
D3A024
D3A025
D3A026
D3A029
D3A090
D3A091
D3A092
D3A093
D3A094
D3A095
D3A096
D3A098
D3A8
D400
D4010
D4011
D4012
D408
D409
D4100
D4101
D4102
D4110
D4111
D4112
D4120
D4121
D4122
D413
D414
D418
D419
D420
D421
D429
D430
D431
D432
D433
D434
D438
D439
D440
D4410
D4411
D4412
D442
D443
D444
D445
D446
D447
D449
D45
D460
D461
D4620
D4621
D4622
D464
D469
D46A
D46B
D46C
D46Z
D470
D471
D472
D473
D474
D479
D47Z1
D47Z9
D480
D481
D482
D483
D484
D485
D4860
D4861
D4862
D487
D489
D490
D491
D492
D493
D494
D495
D496
D497
D4981
D4989
D499
D500
D501
D508
D509
D510
D511
D512
D513
D518
D519
D520
D521
D528
D529
D530
D531
D532
D538
D539
D550
D551
D552
D553
D558
D559
D560
D561
D562
D563
D564
D565
D568
D569
D5700
D5701
D5702
D571
D5720
D57211
D57212
D57219
D573
D5740
D57411
D57412
D57419
D5780
D57811
D57812
D57819
D580
D581
D582
D588
D589
D590
D591
D592
D593
D594
D595
D596
D598
D599
D600
D601
D608
D609
D6101
D6109
D611
D612
D613
D61810
D61811
D61818
D6182
D6189
D619
D62
D630
D631
D638
D640
D641
D642
D643
D644
D6481
D6489
D649
D65
D66
D67
D680
D681
D682
D68311
D68312
D68318
D6832
D684
D6851
D6852
D6859
D6861
D6862
D6869
D688
D689
D690
D691
D692
D693
D6941
D6942
D6949
D6951
D6959
D696
D698
D699
D700
D701
D702
D703
D704
D708
D709
D71
D720
D721
D72810
D72818
D72819
D72820
D72821
D72822
D72823
D72824
D72825
D72828
D72829
D7289
D729
D730
D731
D732
D733
D734
D735
D7381
D7389
D739
D740
D748
D749
D750
D751
D7581
D7582
D7589
D759
D761
D762
D763
D77
D7801
D7802
D7811
D7812
D7821
D7822
D7881
D7889
D800
D801
D802
D803
D804
D805
D806
D807
D808
D809
D810
D811
D812
D813
D814
D815
D816
D817
D81810
D81818
D81819
D8189
D819
D820
D821
D822
D823
D824
D828
D829
D830
D831
D832
D838
D839
D840
D841
D848
D849
D860
D861
D862
D863
D8681
D8682
D8683
D8684
D8685
D8686
D8687
D8689
D869
D890
D891
D892
D893
D89810
D89811
D89812
D89813
D8982
D8989
D899
E000
E001
E002
E009
E010
E011
E012
E018
E02
E030
E031
E032
E033
E034
E035
E038
E039
E040
E041
E042
E048
E049
E0500
E0501
E0510
E0511
E0520
E0521
E0530
E0531
E0540
E0541
E0580
E0581
E0590
E0591
E060
E061
E062
E063
E064
E065
E069
E070
E071
E0781
E0789
E079
E0800
E0801
E0810
E0811
E0821
E0822
E0829
E08311
E08319
E08321
E08329
E08331
E08339
E08341
E08349
E08351
E08359
E0836
E0839
E0840
E0841
E0842
E0843
E0844
E0849
E0851
E0852
E0859
E08610
E08618
E08620
E08621
E08622
E08628
E08630
E08638
E08641
E08649
E0865
E0869
E088
E089
E0900
E0901
E0910
E0911
E0921
E0922
E0929
E09311
E09319
E09321
E09329
E09331
E09339
E09341
E09349
E09351
E09359
E0936
E0939
E0940
E0941
E0942
E0943
E0944
E0949
E0951
E0952
E0959
E09610
E09618
E09620
E09621
E09622
E09628
E09630
E09638
E09641
E09649
E0965
E0969
E098
E099
E1010
E1011
E1021
E1022
E1029
E10311
E10319
E10321
E10329
E10331
E10339
E10341
E10349
E10351
E10359
E1036
E1039
E1040
E1041
E1042
E1043
E1044
E1049
E1051
E1052
E1059
E10610
E10618
E10620
E10621
E10622
E10628
E10630
E10638
E10641
E10649
E1065
E1069
E108
E109
E1100
E1101
E1121
E1122
E1129
E11311
E11319
E11321
E11329
E11331
E11339
E11341
E11349
E11351
E11359
E1136
E1139
E1140
E1141
E1142
E1143
E1144
E1149
E1151
E1152
E1159
E11610
E11618
E11620
E11621
E11622
E11628
E11630
E11638
E11641
E11649
E1165
E1169
E118
E119
E1300
E1301
E1310
E1311
E1321
E1322
E1329
E13311
E13319
E13321
E13329
E13331
E13339
E13341
E13349
E13351
E13359
E1336
E1339
E1340
E1341
E1342
E1343
E1344
E1349
E1351
E1352
E1359
E13610
E13618
E13620
E13621
E13622
E13628
E13630
E13638
E13641
E13649
E1365
E1369
E138
E139
E15
E160
E161
E162
E163
E164
E168
E169
E200
E201
E208
E209
E210
E211
E212
E213
E214
E215
E220
E221
E222
E228
E229
E230
E231
E232
E233
E236
E237
E240
E241
E242
E243
E244
E248
E249
E250
E258
E259
E2601
E2602
E2609
E261
E2681
E2689
E269
E270
E271
E272
E273
E2740
E2749
E275
E278
E279
E280
E281
E282
E28310
E28319
E2839
E288
E289
E290
E291
E298
E299
E300
E301
E308
E309
E310
E311
E3120
E3121
E3122
E3123
E318
E319
E320
E321
E328
E329
E340
E341
E342
E343
E344
E3450
E3451
E3452
E348
E349
E35
E3601
E3602
E3611
E3612
E368
E40
E41
E42
E43
E440
E441
E45
E46
E500
E501
E502
E503
E504
E505
E506
E507
E508
E509
E5111
E5112
E512
E518
E519
E52
E530
E531
E538
E539
E54
E550
E559
E560
E561
E568
E569
E58
E59
E60
E610
E611
E612
E613
E614
E615
E616
E617
E618
E619
E630
E631
E638
E639
E640
E641
E642
E643
E648
E649
E65
E6601
E6609
E661
E662
E663
E668
E669
E670
E671
E672
E673
E678
E68
E700
E701
E7020
E7021
E7029
E7030
E70310
E70311
E70318
E70319
E70320
E70321
E70328
E70329
E70330
E70331
E70338
E70339
E7039
E7040
E7041
E7049
E705
E708
E709
E710
E71110
E71111
E71118
E71120
E71121
E71128
E7119
E712
E7130
E71310
E71311
E71312
E71313
E71314
E71318
E7132
E7139
E7140
E7141
E7142
E7143
E71440
E71448
E7150
E71510
E71511
E71518
E71520
E71521
E71522
E71528
E71529
E7153
E71540
E71541
E71542
E71548
E7200
E7201
E7202
E7203
E7204
E7209
E7210
E7211
E7212
E7219
E7220
E7221
E7222
E7223
E7229
E723
E724
E7250
E7251
E7252
E7253
E7259
E728
E729
E730
E731
E738
E739
E7400
E7401
E7402
E7403
E7404
E7409
E7410
E7411
E7412
E7419
E7420
E7421
E7429
E7431
E7439
E744
E748
E749
E7500
E7501
E7502
E7509
E7510
E7511
E7519
E7521
E7522
E7523
E75240
E75241
E75242
E75243
E75248
E75249
E7525
E7529
E753
E754
E755
E756
E7601
E7602
E7603
E761
E76210
E76211
E76219
E7622
E7629
E763
E768
E769
E770
E771
E778
E779
E780
E781
E782
E783
E784
E785
E786
E7870
E7871
E7872
E7879
E7881
E7889
E789
E790
E791
E792
E798
E799
E800
E801
E8020
E8021
E8029
E803
E804
E805
E806
E807
E8300
E8301
E8309
E8310
E83110
E83111
E83118
E83119
E8319
E832
E8330
E8331
E8332
E8339
E8340
E8341
E8342
E8349
E8350
E8351
E8352
E8359
E8381
E8389
E839
E840
E8411
E8419
E848
E849
E850
E851
E852
E853
E854
E858
E859
E860
E861
E869
E870

In [24]:
from collections import defaultdict
diseases_reasons = defaultdict(list)
for disease_id, icd10 in df_disease_valid[['id', 'ICD-10']].values:
# for disease_id in df_disease_valid['id']:
    reasons = abductive_reasoning(disease_id, disease_gene, gene_protein)
    if len(reasons) == 0:
        continue
    
    icd10 = str(icd10).replace('.', '')
    if icd10 in icd_mapping:
        icd9 = icd_mapping[icd10]
    else:
        print("not found:", icd10)
        continue

    diseases_reasons[icd9].extend(reasons)

not found: F803
not found: C740
not found: E752
not found: E702
not found: E880
not found: G122
not found: E345
not found: D610
not found: D467
not found: D570;D571;D572
not found: E722
not found: Q878
not found: Q878
not found: E752
not found: D830;D839;D831;D832;D838
not found: A810
not found: E840;E841;E848
not found: E888
not found: E720
not found: Q900;Q901;Q902;Q909
not found: H508
not found: B07
not found: Q641
not found: E752
not found: D610
not found: A818
not found: E741
not found: E751
not found: A818
not found: E740
not found: M895
not found: O142
not found: E830
not found: I778
not found: D377;C254;D137
not found: I458
not found: H185
not found: H498
not found: G403
not found: Q878
not found: Q878
not found: C924
not found: C97
not found: M320;M321;M328;M329
not found: C821;C822;C823;C824;C825;C826;C827;C829;C820
not found: C831
not found: T883
not found: Q874
not found: Q878
not found: E762
not found: D448
not found: D448
not found: C900
not found: G403
not found: G711
not found: G474
not found: C749
not found: Q850;Q871
not found: E752
not found: E752
not found: E720
not found: Q878
not found: E713
not found: E703
not found: E240;D352
not found: E802
not found: H355
not found: C692
not found: H351
not found: I458
not found: D860;D861;D869;D862;D863;D868
not found: C841
not found: A16;A15
not found: G403
not found: C64
not found: M313
not found: M148*;K908+
not found: Q938
not found: C64
not found: Q878
not found: E752
not found: E762
not found: G711
not found: Q878
not found: G404
not found: H535
not found: E703
not found: Q878
not found: E711
not found: Q878
not found: E722
not found: E702
not found: E713
not found: Q878
not found: E703
not found: G98
not found: E711
not found: E880
not found: E725
not found: D180
not found: G408
not found: G404
not found: H536
not found: H312
not found: I678
not found: G403
not found: E711
not found: C110;C111;C112;C113
not found: Q878
not found: E274
not found: E888
not found: Q923
not found: G318
not found: G318
not found: Q878
not found: Q850
not found: H472
not found: Q878
not found: H260
not found: Q840;Q828
not found: Q138
not found: Q878
not found: Q878
not found: Q878
not found: Q878
not found: Q878
not found: Q878
not found: G122
not found: D224;D225;D226;D223;D227
not found: Q878
not found: Q878
not found: Q878
not found: Q878
not found: Q878
not found: Q138
not found: G318
not found: Q878
not found: D448
not found: Q878
not found: Q878
not found: H355
not found: Q878
not found: G318
not found: D610
not found: Q878
not found: D610
not found: Q878
not found: E741
not found: E711
not found: H355
not found: Q878
not found: D180
not found: E711
not found: E713
not found: E713
not found: Q138
not found: E720
not found: E721
not found: E888
not found: D694
not found: E831
not found: E888
not found: C25
not found: D70
not found: J841
not found: E830
not found: H350
not found: D610
not found: E713
not found: E888
not found: H355
not found: D233;D234;D235
not found: C449
not found: D234;D235
not found: O266
not found: D898
not found: E711
not found: G938
not found: C343;C349;C342;C348;C341
not found: E831
not found: E742
not found: E711
not found: E725
not found: K768
not found: H312
not found: H536
not found: Q878
not found: C693
not found: H355
not found: E720
not found: E743
not found: Q878
not found: E888
not found: K908
not found: E888
not found: E831
not found: Q531
not found: E888
not found: D818
not found: E703
not found: Q878
not found: Q878
not found: D311
not found: D233;D234;D236
not found: E703
not found: E703
not found: E703
not found: E703
not found: D234;D235
not found: E703
not found: E703
not found: K768
not found: E802
not found: E802
not found: K768
not found: K768
not found: K768
not found: M895
not found: Q878
not found: Q878
not found: Q878
not found: C836
not found: E752
not found: M898
not found: Q874
not found: E854+;I680*
not found: G122
not found: Q701
not found: Q878
not found: Q850
not found: N258
not found: H185
not found: H185
not found: H185
not found: H185
not found: H185
not found: E835
not found: E835
not found: G310
not found: E854+;I680*
not found: O992;E058
not found: G473
not found: E740
not found: E740
not found: E740
not found: E752
not found: G711
not found: H355
not found: G122
not found: E721
not found: E888
not found: C449
not found: E830
not found: M218
not found: E722
not found: Q360;Q361;Q369
not found: Q370;Q374;Q375;Q378;Q379;Q371;Q372;Q373
not found: G403
not found: G404
not found: G618
not found: M911
not found: G404
not found: Q878
not found: G473
not found: M615
not found: M894
not found: Q070
not found: O142;O149;O140;O141
not found: E702
not found: E720
not found: E725
not found: C921
not found: N258
not found: D610
not found: E702
not found: K808
not found: E702
not found: J840
not found: D818
not found: E743
not found: G122
not found: H535
not found: D898
not found: Q878
not found: E760
not found: H185
not found: H401
not found: Q878
not found: E752
not found: E751
not found: E752
not found: G258
not found: E078
not found: H472
not found: G404
not found: E720
not found: Q850
not found: E703
not found: Q788;G711
not found: E721
not found: E888
not found: M898
not found: E721
not found: M880;M888;M889
not found: H494
not found: H260
not found: E740
not found: E741
not found: D70
not found: E740
not found: E711
not found: G728
not found: N258
not found: N258
not found: E830
not found: G404
not found: I678
not found: G404
not found: G404
not found: E888
not found: E703
not found: Q878
not found: E260
not found: Q138
not found: D694
not found: Q138
not found: Q878
not found: I458
not found: Q878
not found: G408
not found: E713
not found: Q878
not found: E713
not found: Q878
not found: Q878
not found: Q878
not found: Q273
not found: E888
not found: E888
not found: E888
not found: Q360;Q361;Q369
not found: M111
not found: Q878
not found: Q878
not found: E833
not found: Q878
not found: Q878
not found: Q923
not found: G122
not found: G122
not found: Q878
not found: Q878
not found: D180
not found: M894
not found: Q878
not found: M858
not found: H355
not found: K137
not found: Q878
not found: Q878
not found: Q878
not found: E752
not found: Q878
not found: Q518
not found: Q878
not found: I778
not found: E722
not found: E722
not found: E833
not found: E725
not found: Q878
not found: E834
not found: E721
not found: Q878
not found: Q878
not found: Q878
not found: Q718
not found: M932
not found: E888
not found: E888
not found: H494
not found: E888
not found: E888
not found: E888
not found: Q878
not found: M895
not found: D43
not found: Q700
not found: Q878
not found: Q878
not found: Q878
not found: Q878
not found: G403
not found: Q878
not found: F711
not found: Q878
not found: Q878
not found: Q878
not found: E740
not found: J840
not found: D448
not found: G310
not found: Q878
not found: Q878
not found: Q878
not found: G258
not found: D728
not found: E752
not found: Q764
not found: D818
not found: E740
not found: B004+;G051*
not found: E713
not found: E752
not found: G400
not found: E713
not found: E711
not found: G122
not found: E752
not found: E752
not found: I710
not found: E740
not found: Q878
not found: H330
not found: Q878
not found: Q878
not found: N041;N043;N048
not found: C435;C436;C437;C438;C430;C432;C431;C434;C433
not found: Q878
not found: E740
not found: D475
not found: Q923
not found: G318
not found: E713
not found: E721
not found: E722
not found: C509;C56
not found: Q878
not found: C501;C502;C503;C504;C505;C506;C508;C500
not found: E713
not found: E713
not found: E713
not found: G403
not found: G318
not found: D467;D560
not found: E835
not found: H355
not found: H355
not found: D818
not found: H355
not found: Q923
not found: Q878
not found: H355
not found: D898
not found: M863
not found: E752
not found: Q878
not found: H355
not found: H355
not found: E703
not found: E721
not found: E711
not found: H185
not found: G122
not found: D70
not found: E740
not found: E740
not found: E711
not found: E711
not found: E888
not found: H350
not found: E752
not found: Q878
not found: E888
not found: E721
not found: E721
not found: E721
not found: E711
not found: E740
not found: E752
not found: E750
not found: E752
not found: E752
not found: E752
not found: E762
not found: E762
not found: E750
not found: E750
not found: E750
not found: Q700;Q702
not found: N082
not found: H208;H308
not found: E720+;N163*
not found: E720
not found: E720+;N163*
not found: D818
not found: D683
not found: G938
not found: G318
not found: E713
not found: E260
not found: E713
not found: G934
not found: C64
not found: E788
not found: K743;M348
not found: G404
not found: E834
not found: G404
not found: E713
not found: C349
not found: G318
not found: E711
not found: D694
not found: E762
not found: E711
not found: J47
not found: Q874
not found: H355
not found: E711
not found: M858
not found: G408
not found: E752
not found: Q878
not found: Q878
not found: H355
not found: E752
not found: E752
not found: D694
not found: I99
not found: E713
not found: Q878
not found: G403
not found: G404
not found: E740
not found: E834
not found: H355
not found: H355
not found: Q878
not found: H498
not found: G122
not found: I738
not found: E833
not found: Q878
not found: Q878
not found: Q878
not found: E711
not found: E721
not found: E833
not found: Q725
not found: Q878
not found: E345
not found: E703
not found: E802
not found: E762
not found: E751
not found: E751
not found: E740
not found: E740
not found: E742
not found: E742
not found: E721
not found: E721
not found: E762
not found: E762
not found: E762
not found: M815
not found: M858
not found: Q878
not found: E752
not found: Q878
not found: Q878
not found: Q878
not found: Q878
not found: Q878
not found: M084
not found: M082
not found: D70
not found: H312
not found: Q104;Q384
not found: Q878
not found: D467
not found: E888
not found: Q878
not found: Q878
not found: K528
not found: E888
not found: H355
not found: M068
not found: Q878
not found: D448
not found: Q878
not found: E740
not found: Q850
not found: Q878
not found: E760
not found: N258
not found: N258
not found: N258
not found: E268
not found: G711
not found: H185
not found: H185
not found: H185
not found: H185
not found: H185
not found: H355
not found: E752
not found: G400
not found: E743
not found: G400
not found: H185
not found: G310
not found: E854+;I680*
not found: C154;C153;C151;C150
not found: C152;C155
not found: E713
not found: E740
not found: G934
not found: E713
not found: G934
not found: Q878
not found: Q878
not found: Q878
not found: Q878
not found: G408
not found: E703
not found: J931
not found: E740
not found: D70
not found: E711
not found: G431
not found: Q878
not found: E713
not found: E752
not found: H355
not found: E788
not found: D572
not found: E260
not found: E888
not found: H494
not found: Q878
not found: Q923
not found: Q878
not found: E888
not found: E740
not found: Q878
not found: G310
not found: A818
not found: Q764
not found: D350;C741
not found: D467
not found: D685
not found: E058
not found: G938
not found: E713
not found: C840
not found: Q878
not found: Q043;Q615
not found: H355;Q043
not found: G233
not found: E720
not found: Q923
not found: D898
not found: Q878
not found: Q878
not found: D694
not found: D685
not found: G258
not found: E888
not found: M124
not found: I680*;E854+
not found: E854+;I680*
not found: E854+;I680*
not found: E854+;I680*
not found: Q878
not found: E752
not found: E703
not found: Q878
not found: E260
not found: Q878
not found: Q878
not found: Q878
not found: E752
not found: E752
not found: Q850
not found: Q878
not found: G404
not found: Q878
not found: H508
not found: G938
not found: G258
not found: G403
not found: G403
not found: F841
not found: Q878
not found: Q878
not found: I778
not found: G400
not found: Q878
not found: Q874
not found: E721
not found: E833
not found: Q878
not found: Q878
not found: Q878
not found: A810
not found: M858
not found: G122
not found: D898
not found: Q878
not found: E831
not found: Q878
not found: Q878
not found: Q878
not found: Q878
not found: Q878
not found: Q923
not found: Q878
not found: Q878
not found: F788
not found: Q878
not found: Q878
not found: T883
not found: Q878
not found: G938
not found: E888
not found: H472
not found: E888
not found: Q878
not found: Q878
not found: G404
not found: M895
not found: Q878
not found: Q878
not found: Q878
not found: Q878
not found: N46
not found: M898
not found: Q878
not found: E888
not found: Q878
not found: E713
not found: E752
not found: G404
not found: Q878
not found: E888
not found: C180;C181;C182;C183;C184;C185;C186;C187
not found: G404
not found: C809
not found: E888
not found: Q878
not found: D898
not found: G318
not found: E752
not found: G318
not found: C741;C755;D350;D356
not found: G404
not found: E711
not found: Q878
not found: E888
not found: Q878
not found: Q878
not found: Q878
not found: Q878
not found: G318
not found: G318
not found: Q878
not found: G404
not found: I489
not found: F781
not found: Q878
not found: Q878
not found: E888
not found: Q878
not found: Q923
not found: E888
not found: Q878
not found: E888
not found: Q878
not found: Q878
not found: Q878
not found: Q878
not found: G403
not found: M850
not found: E888
not found: Q878
not found: Q878
not found: M858
not found: K768
not found: E888
not found: G404
not found: E274
not found: Q878
not found: Q878
not found: E268
not found: G934
not found: Q878
not found: E838
not found: Q714
not found: Q878
not found: E703
not found: E751
not found: E711
not found: Q878
not found: Q878
not found: G403
not found: M878
not found: G474
not found: Q542;Q543
not found: E030;E031
not found: N258
not found: M320;M321;M328;M329
not found: E760
not found: G938
not found: Q878
not found: Q878
not found: Q878
not found: E345
not found: G711
not found: Q878
not found: G711
not found: G711
not found: G400
not found: D467
not found: H472
not found: Q878
not found: E888
not found: E802
not found: T783

In [25]:
len(diseases_reasons)

317

In [48]:
mimic_icd9 = pd.read_csv("DIAGNOSES_ICD.csv")
mimic_icd9 = set(mimic_icd9['ICD9_CODE'])

In [49]:
len(mimic_icd9)

6985

In [28]:
_diseases_reasons = {}
for k, v in diseases_reasons.items():
    if k in mimic_icd9:
        _diseases_reasons[k] = v
diseases_reasons = _diseases_reasons

In [29]:
len(diseases_reasons)

258

In [30]:
diseases_reasons

{'75839': [('GENE:27214', ['PROTEIN:6548']),
  ('GENE:32979', ['PROTEIN:12455']),
  ('GENE:33448', ['PROTEIN:21970']),
  ('GENE:26178', ['PROTEIN:2126']),
  ('GENE:29712', ['PROTEIN:19712']),
  ('GENE:33530', ['PROTEIN:6141']),
  ('GENE:33531', ['PROTEIN:16612']),
  ('GENE:25133', ['PROTEIN:11602']),
  ('GENE:31252', ['PROTEIN:10825']),
  ('GENE:25090', ['PROTEIN:10887']),
  ('GENE:25090', ['PROTEIN:10887']),
  ('GENE:35649', ['PROTEIN:1742']),
  ('GENE:35649', ['PROTEIN:1742']),
  ('GENE:26843', ['PROTEIN:10307']),
  ('GENE:30694', ['PROTEIN:15222']),
  ('GENE:25464', ['PROTEIN:271']),
  ('GENE:25464', ['PROTEIN:271']),
  ('GENE:28937', ['PROTEIN:82']),
  ('GENE:31669', ['PROTEIN:6051']),
  ('GENE:32797', ['PROTEIN:12522']),
  ('GENE:34633', ['PROTEIN:11934']),
  ('GENE:25030', ['PROTEIN:18347']),
  ('GENE:27163', ['PROTEIN:12055']),
  ('GENE:32600', ['PROTEIN:16803']),
  ('GENE:27301', ['PROTEIN:18552']),
  ('GENE:27301', ['PROTEIN:18552']),
  ('GENE:28019', ['PROTEIN:14633']),
  ('GENE:28022', ['PROTEIN:8647']),
  ('GENE:33383', ['PROTEIN:1244']),
  ('GENE:34134', ['PROTEIN:15102']),
  ('GENE:25703', ['PROTEIN:15101']),
  ('GENE:32386', ['PROTEIN:1284']),
  ('GENE:26006', ['PROTEIN:7164']),
  ('GENE:28276', ['PROTEIN:11933']),
  ('GENE:31945', ['PROTEIN:21541']),
  ('GENE:25568', ['PROTEIN:20857']),
  ('GENE:26382', ['PROTEIN:18662']),
  ('GENE:25568', ['PROTEIN:20857']),
  ('GENE:26382', ['PROTEIN:18662']),
  ('GENE:27753', ['PROTEIN:17030']),
  ('GENE:31293', ['PROTEIN:6112']),
  ('GENE:32839', ['PROTEIN:20246']),
  ('GENE:33875', ['PROTEIN:17670']),
  ('GENE:32242', ['PROTEIN:6587']),
  ('GENE:27301', ['PROTEIN:18552']),
  ('GENE:28341', ['PROTEIN:17439']),
  ('GENE:27866', ['PROTEIN:10367']),
  ('GENE:31997', ['PROTEIN:11412']),
  ('GENE:34836', ['PROTEIN:6273']),
  ('GENE:34836', ['PROTEIN:6273']),
  ('GENE:27110', ['PROTEIN:11776']),
  ('GENE:27762', ['PROTEIN:8012']),
  ('GENE:27762', ['PROTEIN:8012']),
  ('GENE:32806', ['PROTEIN:14463']),
  ('GENE:33176', ['PROTEIN:16344']),
  ('GENE:31852', ['PROTEIN:18063']),
  ('GENE:26613', ['PROTEIN:4025']),
  ('GENE:31611', ['PROTEIN:10620']),
  ('GENE:29908', ['PROTEIN:15020']),
  ('GENE:28867', ['PROTEIN:18013']),
  ('GENE:28276', ['PROTEIN:11933']),
  ('GENE:28863', ['PROTEIN:4446']),
  ('GENE:26568', ['PROTEIN:2419']),
  ('GENE:30267', ['PROTEIN:21327']),
  ('GENE:33448', ['PROTEIN:21970']),
  ('GENE:32979', ['PROTEIN:12455']),
  ('GENE:33448', ['PROTEIN:21970']),
  ('GENE:31931', ['PROTEIN:8454']),
  ('GENE:27072', ['PROTEIN:9396']),
  ('GENE:33095', ['PROTEIN:21783']),
  ('GENE:33688', ['PROTEIN:6158']),
  ('GENE:31923', ['PROTEIN:12355']),
  ('GENE:34069', ['PROTEIN:8881']),
  ('GENE:27444', ['PROTEIN:21238']),
  ('GENE:33448', ['PROTEIN:21970']),
  ('GENE:30381', ['PROTEIN:20064']),
  ('GENE:33448', ['PROTEIN:21970'])],
 '2725': [('GENE:30136', ['PROTEIN:1576']),
  ('GENE:30136', ['PROTEIN:1576']),
  ('GENE:26633', ['PROTEIN:710']),
  ('GENE:28943', ['PROTEIN:1754']),
  ('GENE:26633', ['PROTEIN:710']),
  ('GENE:26633', ['PROTEIN:710']),
  ('GENE:30605', ['PROTEIN:3536']),
  ('GENE:30605', ['PROTEIN:3536']),
  ('GENE:29696', ['PROTEIN:21188']),
  ('GENE:29696', ['PROTEIN:21188']),
  ('GENE:29696', ['PROTEIN:21188'])],
 '7564': [('GENE:27045', ['PROTEIN:3759']),
  ('GENE:27045', ['PROTEIN:3759']),
  ('GENE:31092', ['PROTEIN:13998']),
  ('GENE:32264', ['PROTEIN:4311']),
  ('GENE:32264', ['PROTEIN:4311']),
  ('GENE:30332', ['PROTEIN:1820']),
  ('GENE:30332', ['PROTEIN:1820']),
  ('GENE:26951', ['PROTEIN:8766']),
  ('GENE:26951', ['PROTEIN:8766']),
  ('GENE:29811', ['PROTEIN:10596']),
  ('GENE:25808', ['PROTEIN:93']),
  ('GENE:25808', ['PROTEIN:93']),
  ('GENE:25808', ['PROTEIN:93']),
  ('GENE:29054', ['PROTEIN:1917']),
  ('GENE:29056', ['PROTEIN:1916']),
  ('GENE:31981', ['PROTEIN:3771']),
  ('GENE:27229', ['PROTEIN:10969']),
  ('GENE:29271', ['PROTEIN:6143']),
  ('GENE:27229', ['PROTEIN:10969']),
  ('GENE:25874', ['PROTEIN:1690']),
  ('GENE:25874', ['PROTEIN:1690']),
  ('GENE:25808', ['PROTEIN:93']),
  ('GENE:25808', ['PROTEIN:93']),
  ('GENE:31077', ['PROTEIN:10852']),
  ('GENE:26595', ['PROTEIN:18534']),
  ('GENE:26595', ['PROTEIN:18534']),
  ('GENE:25808', ['PROTEIN:93']),
  ('GENE:26595', ['PROTEIN:18534']),
  ('GENE:26595', ['PROTEIN:18534']),
  ('GENE:35336', ['PROTEIN:9776']),
  ('GENE:35336', ['PROTEIN:9776']),
  ('GENE:32264', ['PROTEIN:4311']),
  ('GENE:32264', ['PROTEIN:4311']),
  ('GENE:25808', ['PROTEIN:93']),
  ('GENE:27317', ['PROTEIN:1778']),
  ('GENE:25808', ['PROTEIN:93']),
  ('GENE:27317', ['PROTEIN:1778']),
  ('GENE:28372', ['PROTEIN:460']),
  ('GENE:28372', ['PROTEIN:460']),
  ('GENE:25808', ['PROTEIN:93']),
  ('GENE:25808', ['PROTEIN:93']),
  ('GENE:29475', ['PROTEIN:21167']),
  ('GENE:29475', ['PROTEIN:21167']),
  ('GENE:27045', ['PROTEIN:3759']),
  ('GENE:27045', ['PROTEIN:3759']),
  ('GENE:27222', ['PROTEIN:4443']),
  ('GENE:27222', ['PROTEIN:4443']),
  ('GENE:29054', ['PROTEIN:1917']),
  ('GENE:29056', ['PROTEIN:1916']),
  ('GENE:26595', ['PROTEIN:18534']),
  ('GENE:26595', ['PROTEIN:18534']),
  ('GENE:26541', ['PROTEIN:2394']),
  ('GENE:26541', ['PROTEIN:2394']),
  ('GENE:29868', ['PROTEIN:12032']),
  ('GENE:29868', ['PROTEIN:12032']),
  ('GENE:27045', ['PROTEIN:3759']),
  ('GENE:27045', ['PROTEIN:3759']),
  ('GENE:25858', ['PROTEIN:11585']),
  ('GENE:25860', ['PROTEIN:20808']),
  ('GENE:32101', ['PROTEIN:2757']),
  ('GENE:32101', ['PROTEIN:2757']),
  ('GENE:29797', ['PROTEIN:18143']),
  ('GENE:28884', ['PROTEIN:20643']),
  ('GENE:29797', ['PROTEIN:18143']),
  ('GENE:32119', ['PROTEIN:16629']),
  ('GENE:30551', ['PROTEIN:20376']),
  ('GENE:31077', ['PROTEIN:10852']),
  ('GENE:35107', ['PROTEIN:16714']),
  ('GENE:26541', ['PROTEIN:2394']),
  ('GENE:26541', ['PROTEIN:2394']),
  ('GENE:27045', ['PROTEIN:3759']),
  ('GENE:27045', ['PROTEIN:3759']),
  ('GENE:32526', ['PROTEIN:19988']),
  ('GENE:25808', ['PROTEIN:93']),
  ('GENE:25808', ['PROTEIN:93']),
  ('GENE:29970', ['PROTEIN:1389']),
  ('GENE:29970', ['PROTEIN:1389']),
  ('GENE:32933', ['PROTEIN:16083']),
  ('GENE:32933', ['PROTEIN:16083']),
  ('GENE:25808', ['PROTEIN:93']),
  ('GENE:30684', ['PROTEIN:274']),
  ('GENE:30684', ['PROTEIN:274']),
  ('GENE:25808', ['PROTEIN:93']),
  ('GENE:25808', ['PROTEIN:93']),
  ('GENE:27045', ['PROTEIN:3759']),
  ('GENE:27045', ['PROTEIN:3759']),
  ('GENE:30359', ['PROTEIN:1288']),
  ('GENE:25860', ['PROTEIN:20808']),
  ('GENE:28937', ['PROTEIN:82']),
  ('GENE:32603', ['PROTEIN:9758', 'PROTEIN:9759']),
  ('GENE:25808', ['PROTEIN:93'])],
 '7560': [('GENE:27047', ['PROTEIN:80']),
  ('GENE:27047', ['PROTEIN:80']),
  ('GENE:32444', ['PROTEIN:1499']),
  ('GENE:32444', ['PROTEIN:1499']),
  ('GENE:25235', ['PROTEIN:8004']),
  ('GENE:32296', ['PROTEIN:18467']),
  ('GENE:27213', ['PROTEIN:10845']),
  ('GENE:25808', ['PROTEIN:93']),
  ('GENE:25860', ['PROTEIN:20808']),
  ('GENE:27044', ['PROTEIN:81']),
  ('GENE:27047', ['PROTEIN:80']),
  ('GENE:24790', ['PROTEIN:18565']),
  ('GENE:24790', ['PROTEIN:18565']),
  ('GENE:30167', ['PROTEIN:12099']),
  ('GENE:30167', ['PROTEIN:12099']),
  ('GENE:27729', ['PROTEIN:19817']),
  ('GENE:25858', ['PROTEIN:11585']),
  ('GENE:25858', ['PROTEIN:11585']),
  ('GENE:30292', ['PROTEIN:12134']),
  ('GENE:30292', ['PROTEIN:12134']),
  ('GENE:27362', ['PROTEIN:13338']),
  ('GENE:25586', ['PROTEIN:11205']),
  ('GENE:25586', ['PROTEIN:11205']),
  ('GENE:30745', ['PROTEIN:351']),
  ('GENE:31582', ['PROTEIN:1977']),
  ('GENE:26838', ['PROTEIN:16198']),
  ('GENE:25900', ['PROTEIN:9022']),
  ('GENE:26838', ['PROTEIN:16198']),
  ('GENE:25900', ['PROTEIN:9022']),
  ('GENE:34731', ['PROTEIN:15177']),
  ('GENE:25586', ['PROTEIN:11205']),
  ('GENE:25586', ['PROTEIN:11205']),
  ('GENE:28179', ['PROTEIN:7393']),
  ('GENE:26638', ['PROTEIN:3832']),
  ('GENE:28179', ['PROTEIN:7393']),
  ('GENE:31006', ['PROTEIN:19998']),
  ('GENE:24790', ['PROTEIN:18565']),
  ('GENE:30494', ['PROTEIN:13753']),
  ('GENE:30494', ['PROTEIN:13753']),
  ('GENE:28152', ['PROTEIN:11814']),
  ('GENE:28152', ['PROTEIN:11814']),
  ('GENE:33490', ['PROTEIN:5974']),
  ('GENE:34061', ['PROTEIN:18080']),
  ('GENE:33490', ['PROTEIN:5974']),
  ('GENE:34061', ['PROTEIN:18080']),
  ('GENE:26323', ['PROTEIN:17839']),
  ('GENE:26323', ['PROTEIN:17839']),
  ('GENE:35034', ['PROTEIN:21971']),
  ('GENE:35034', ['PROTEIN:21971']),
  ('GENE:33174', ['PROTEIN:3291']),
  ('GENE:33174', ['PROTEIN:3291']),
  ('GENE:26951', ['PROTEIN:8766']),
  ('GENE:29810', ['PROTEIN:10595']),
  ('GENE:34156', ['PROTEIN:8471']),
  ('GENE:27045', ['PROTEIN:3759']),
  ('GENE:27045', ['PROTEIN:3759']),
  ('GENE:27222', ['PROTEIN:4443']),
  ('GENE:27222', ['PROTEIN:4443']),
  ('GENE:35507', ['PROTEIN:15366']),
  ('GENE:30574', ['PROTEIN:12442', 'PROTEIN:15368']),
  ('GENE:34408', ['PROTEIN:21625']),
  ('GENE:27047', ['PROTEIN:80']),
  ('GENE:33404', ['PROTEIN:11204']),
  ('GENE:27045', ['PROTEIN:3759']),
  ('GENE:27047', ['PROTEIN:80']),
  ('GENE:33404', ['PROTEIN:11204']),
  ('GENE:27047', ['PROTEIN:80']),
  ('GENE:27047', ['PROTEIN:80']),
  ('GENE:26515', ['PROTEIN:1578']),
  ('GENE:26515', ['PROTEIN:1578']),
  ('GENE:32994', ['PROTEIN:14023']),
  ('GENE:24671', ['PROTEIN:7031']),
  ('GENE:28869', ['PROTEIN:11868']),
  ('GENE:27021', ['PROTEIN:7401']),
  ('GENE:27021', ['PROTEIN:7401']),
  ('GENE:27814', ['PROTEIN:21829']),
  ('GENE:27814', ['PROTEIN:21829']),
  ('GENE:34558', ['PROTEIN:13683']),
  ('GENE:34558', ['PROTEIN:13683']),
  ('GENE:26847', ['PROTEIN:11739']),
  ('GENE:27129', ['PROTEIN:10890']),
  ('GENE:27129', ['PROTEIN:10890']),
  ('GENE:27130', ['PROTEIN:9409']),
  ('GENE:27655', ['PROTEIN:16880']),
  ('GENE:25827', ['PROTEIN:12624']),
  ('GENE:27044', ['PROTEIN:81']),
  ('GENE:32309', ['PROTEIN:3444']),
  ('GENE:33274', ['PROTEIN:4328']),
  ('GENE:30056', ['PROTEIN:323']),
  ('GENE:30862', ['PROTEIN:21557']),
  ('GENE:30862', ['PROTEIN:21557']),
  ('GENE:30067', ['PROTEIN:15054']),
  ('GENE:30067', ['PROTEIN:15054']),
  ('GENE:35355', ['PROTEIN:17238']),
  ('GENE:35355', ['PROTEIN:17238']),
  ('GENE:27045', ['PROTEIN:3759']),
  ('GENE:33182', ['PROTEIN:18016']),
  ('GENE:33404', ['PROTEIN:11204']),
  ('GENE:26816', ['PROTEIN:14722']),
  ('GENE:33404', ['PROTEIN:11204']),
  ('GENE:24934', ['PROTEIN:21667']),
  ('GENE:24934', ['PROTEIN:21667']),
  ('GENE:27045', ['PROTEIN:3759']),
  ('GENE:27045', ['PROTEIN:3759']),
  ('GENE:27222', ['PROTEIN:4443']),
  ('GENE:26816', ['PROTEIN:14722']),
  ('GENE:27047', ['PROTEIN:80']),
  ('GENE:29799', ['PROTEIN:18144']),
  ('GENE:32948', ['PROTEIN:1551']),
  ('GENE:30501', ['PROTEIN:575']),
  ('GENE:32444', ['PROTEIN:1499']),
  ('GENE:31561', ['PROTEIN:9284']),
  ('GENE:33755', ['PROTEIN:14115']),
  ('GENE:32393', ['PROTEIN:4450']),
  ('GENE:27540', ['PROTEIN:1059']),
  ('GENE:31379', ['PROTEIN:2599']),
  ('GENE:28043', ['PROTEIN:10349']),
  ('GENE:25316', ['PROTEIN:9000']),
  ('GENE:28501', ['PROTEIN:17155']),
  ('GENE:27775', ['PROTEIN:19117']),
  ('GENE:32200', ['PROTEIN:1521']),
  ('GENE:24803', ['PROTEIN:15504']),
  ('GENE:33136', ['PROTEIN:8115']),
  ('GENE:26847', ['PROTEIN:11739']),
  ('GENE:27047', ['PROTEIN:80']),
  ('GENE:27047', ['PROTEIN:80']),
  ('GENE:27044', ['PROTEIN:81']),
  ('GENE:27047', ['PROTEIN:80']),
  ('GENE:25267', ['PROTEIN:15987'])],
 '2530': [('GENE:35094', ['PROTEIN:14369']),
  ('GENE:29916', ['PROTEIN:6167']),
  ('GENE:35094', ['PROTEIN:14369'])],
 '75169': [('GENE:26580', ['PROTEIN:19607'])],
 '28243': [('GENE:28624', ['PROTEIN:1454']),
  ('GENE:28625', ['PROTEIN:1454']),
  ('GENE:28626', ['PROTEIN:1453']),
  ('GENE:28624', ['PROTEIN:1454']),
  ('GENE:28625', ['PROTEIN:1454']),
  ('GENE:31188', ['PROTEIN:20667']),
  ('GENE:31188', ['PROTEIN:20667']),
  ('GENE:28624', ['PROTEIN:1454']),
  ('GENE:28625', ['PROTEIN:1454']),
  ('GENE:28624', ['PROTEIN:1454']),
  ('GENE:28625', ['PROTEIN:1454'])],
 '74722': [('GENE:26735', ['PROTEIN:1202']), ('GENE:26735', ['PROTEIN:1202'])],
 '2727': [('GENE:26534', ['PROTEIN:19065']),
  ('GENE:26534', ['PROTEIN:19065']),
  ('GENE:29853', ['PROTEIN:6170']),
  ('GENE:29852', ['PROTEIN:6166']),
  ('GENE:27554', ['PROTEIN:6173']),
  ('GENE:27554', ['PROTEIN:6173']),
  ('GENE:31222', ['PROTEIN:6428']),
  ('GENE:31222', ['PROTEIN:6428']),
  ('GENE:24587', ['PROTEIN:11812']),
  ('GENE:24587', ['PROTEIN:11812']),
  ('GENE:27920', ['PROTEIN:6647']),
  ('GENE:30258', ['PROTEIN:825']),
  ('GENE:33813', ['PROTEIN:13815']),
  ('GENE:34925', ['PROTEIN:3546']),
  ('GENE:35227', ['PROTEIN:20090']),
  ('GENE:35227', ['PROTEIN:20090']),
  ('GENE:35389', ['PROTEIN:16026']),
  ('GENE:35389', ['PROTEIN:16026']),
  ('GENE:31111', ['PROTEIN:19322']),
  ('GENE:31111', ['PROTEIN:19322']),
  ('GENE:24981', ['PROTEIN:7966']),
  ('GENE:24981', ['PROTEIN:7966']),
  ('GENE:33813', ['PROTEIN:13815']),
  ('GENE:27080', ['PROTEIN:19317']),
  ('GENE:27080', ['PROTEIN:19317']),
  ('GENE:35235', ['PROTEIN:20810']),
  ('GENE:35235', ['PROTEIN:20810']),
  ('GENE:27986', ['PROTEIN:379']),
  ('GENE:27986', ['PROTEIN:379']),
  ('GENE:33677', ['PROTEIN:15037']),
  ('GENE:33677', ['PROTEIN:15037']),
  ('GENE:29927', ['PROTEIN:15025']),
  ('GENE:29927', ['PROTEIN:15025']),
  ('GENE:33866', ['PROTEIN:20630']),
  ('GENE:33866', ['PROTEIN:20630']),
  ('GENE:31709', ['PROTEIN:9970']),
  ('GENE:31709', ['PROTEIN:9970']),
  ('GENE:34664', ['PROTEIN:9971']),
  ('GENE:34664', ['PROTEIN:9971']),
  ('GENE:33713', ['PROTEIN:20629']),
  ('GENE:33713', ['PROTEIN:20629']),
  ('GENE:33723', ['PROTEIN:6920']),
  ('GENE:33723', ['PROTEIN:6920']),
  ('GENE:35499', ['PROTEIN:18209']),
  ('GENE:35499', ['PROTEIN:18209']),
  ('GENE:34857', ['PROTEIN:17796']),
  ('GENE:34857', ['PROTEIN:17796']),
  ('GENE:24745', ['PROTEIN:17431']),
  ('GENE:24745', ['PROTEIN:17431']),
  ('GENE:28555', ['PROTEIN:14372']),
  ('GENE:28555', ['PROTEIN:14372']),
  ('GENE:29987', ['PROTEIN:6072']),
  ('GENE:29987', ['PROTEIN:6072']),
  ('GENE:31052', ['PROTEIN:18390']),
  ('GENE:31052', ['PROTEIN:18390']),
  ('GENE:26562', ['PROTEIN:6831']),
  ('GENE:26562', ['PROTEIN:6831']),
  ('GENE:34457', ['PROTEIN:20811']),
  ('GENE:34457', ['PROTEIN:20811']),
  ('GENE:27688', ['PROTEIN:7145']),
  ('GENE:24921', ['PROTEIN:17686']),
  ('GENE:30018', ['PROTEIN:17430']),
  ('GENE:34861', ['PROTEIN:19321']),
  ('GENE:33889', ['PROTEIN:6921']),
  ('GENE:29327', ['PROTEIN:12598']),
  ('GENE:33058', ['PROTEIN:11087']),
  ('GENE:32630', ['PROTEIN:17307']),
  ('GENE:33459', ['PROTEIN:7967']),
  ('GENE:29852', ['PROTEIN:6166']),
  ('GENE:29852', ['PROTEIN:6166']),
  ('GENE:26445', ['PROTEIN:10782']),
  ('GENE:26843', ['PROTEIN:10307']),
  ('GENE:32625', ['PROTEIN:9518']),
  ('GENE:31607', ['PROTEIN:6775']),
  ('GENE:25386', ['PROTEIN:2158']),
  ('GENE:27056', ['PROTEIN:16027']),
  ('GENE:30939', ['PROTEIN:6906']),
  ('GENE:31252', ['PROTEIN:10825']),
  ('GENE:30258', ['PROTEIN:825']),
  ('GENE:30258', ['PROTEIN:825'])],
 '3348': [('GENE:30238', ['PROTEIN:842']),
  ('GENE:33515', ['PROTEIN:2838']),
  ('GENE:30884', ['PROTEIN:15875']),
  ('GENE:25733', ['PROTEIN:20498']),
  ('GENE:29129', ['PROTEIN:3787']),
  ('GENE:27042', ['PROTEIN:10338']),
  ('GENE:26583', ['PROTEIN:6977']),
  ('GENE:26583', ['PROTEIN:6977']),
  ('GENE:25182', ['PROTEIN:21496']),
  ('GENE:25182', ['PROTEIN:21496']),
  ('GENE:31145', ['PROTEIN:13914']),
  ('GENE:25182', ['PROTEIN:21496']),
  ('GENE:31145', ['PROTEIN:13914']),
  ('GENE:29995', ['PROTEIN:12069']),
  ('GENE:29995', ['PROTEIN:12069']),
  ('GENE:29945', ['PROTEIN:17510']),
  ('GENE:29945', ['PROTEIN:17510']),
  ('GENE:29945', ['PROTEIN:17510']),
  ('GENE:32819', ['PROTEIN:397']),
  ('GENE:32819', ['PROTEIN:397']),
  ('GENE:33680', ['PROTEIN:1103']),
  ('GENE:33680', ['PROTEIN:1103']),
  ('GENE:32516', ['PROTEIN:17511']),
  ('GENE:32516', ['PROTEIN:17511']),
  ('GENE:33165', ['PROTEIN:11133']),
  ('GENE:33165', ['PROTEIN:11133']),
  ('GENE:26114', ['PROTEIN:6714']),
  ('GENE:26114', ['PROTEIN:6714']),
  ('GENE:29945', ['PROTEIN:17510']),
  ('GENE:30906', ['PROTEIN:7810']),
  ('GENE:24961', ['PROTEIN:7723']),
  ('GENE:26360', ['PROTEIN:10220']),
  ('GENE:32078', ['PROTEIN:6183']),
  ('GENE:30594', ['PROTEIN:985']),
  ('GENE:32340', ['PROTEIN:362']),
  ('GENE:30020', ['PROTEIN:20873'])],
 '75989': [('GENE:24805', ['PROTEIN:17614']),
  ('GENE:29136', ['PROTEIN:8923']),
  ('GENE:29428', ['PROTEIN:1639']),
  ('GENE:26810', ['PROTEIN:718']),
  ('GENE:26810', ['PROTEIN:718']),
  ('GENE:31946', ['PROTEIN:3540']),
  ('GENE:25983', ['PROTEIN:2647']),
  ('GENE:29744', ['PROTEIN:6154']),
  ('GENE:29744', ['PROTEIN:6154']),
  ('GENE:32673', ['PROTEIN:21366']),
  ('GENE:28421', ['PROTEIN:12506']),
  ('GENE:32673', ['PROTEIN:21366']),
  ('GENE:26851', ['PROTEIN:4833']),
  ('GENE:26851', ['PROTEIN:4833']),
  ('GENE:34799', ['PROTEIN:6684']),
  ('GENE:27402', ['PROTEIN:6340']),
  ('GENE:32673', ['PROTEIN:21366']),
  ('GENE:27021', ['PROTEIN:7401']),
  ('GENE:28089', ['PROTEIN:7400']),
  ('GENE:27021', ['PROTEIN:7401']),
  ('GENE:28089', ['PROTEIN:7400']),
  ('GENE:33166', ['PROTEIN:15543']),
  ('GENE:34731', ['PROTEIN:15177']),
  ('GENE:34731', ['PROTEIN:15177']),
  ('GENE:32732', ['PROTEIN:5939']),
  ('GENE:29164', ['PROTEIN:12600']),
  ('GENE:30315', ['PROTEIN:6681']),
  ('GENE:31177', ['PROTEIN:19309']),
  ('GENE:32008', ['PROTEIN:13894']),
  ('GENE:32034', ['PROTEIN:13154']),
  ('GENE:35641', ['PROTEIN:21105']),
  ('GENE:30275', ['PROTEIN:9169']),
  ('GENE:30275', ['PROTEIN:9169']),
  ('GENE:29799', ['PROTEIN:18144']),
  ('GENE:29799', ['PROTEIN:18144']),
  ('GENE:33949', ['PROTEIN:16077']),
  ('GENE:33949', ['PROTEIN:16077']),
  ('GENE:29744', ['PROTEIN:6154']),
  ('GENE:25808', ['PROTEIN:93']),
  ('GENE:25808', ['PROTEIN:93']),
  ('GENE:25858', ['PROTEIN:11585']),
  ('GENE:25858', ['PROTEIN:11585']),
  ('GENE:35744', ['PROTEIN:10897']),
  ('GENE:35744', ['PROTEIN:10897']),
  ('GENE:29136', ['PROTEIN:8923']),
  ('GENE:31346', ['PROTEIN:14365']),
  ('GENE:34437', ['PROTEIN:21614']),
  ('GENE:31605', ['PROTEIN:7472']),
  ('GENE:30584', ['PROTEIN:7478']),
  ('GENE:31605', ['PROTEIN:7472']),
  ('GENE:32018', ['PROTEIN:15691']),
  ('GENE:32085', ['PROTEIN:20492']),
  ('GENE:25400', ['PROTEIN:14897']),
  ('GENE:30318', ['PROTEIN:9189']),
  ('GENE:30318', ['PROTEIN:9189']),
  ('GENE:31946', ['PROTEIN:3540']),
  ('GENE:27085', ['PROTEIN:17637']),
  ('GENE:27085', ['PROTEIN:17637']),
  ('GENE:29392', ['PROTEIN:1154']),
  ('GENE:29392', ['PROTEIN:1154']),
  ('GENE:26533', ['PROTEIN:16118']),
  ('GENE:26839', ['PROTEIN:9086']),
  ('GENE:28182', ['PROTEIN:19484']),
  ('GENE:32238', ['PROTEIN:21563']),
  ('GENE:27222', ['PROTEIN:4443']),
  ('GENE:27222', ['PROTEIN:4443']),
  ('GENE:32631', ['PROTEIN:17308']),
  ('GENE:27045', ['PROTEIN:3759']),
  ('GENE:27045', ['PROTEIN:3759']),
  ('GENE:31946', ['PROTEIN:3540']),
  ('GENE:29291', ['PROTEIN:10488']),
  ('GENE:25848', ['PROTEIN:7141']),
  ('GENE:25849', ['PROTEIN:7142']),
  ('GENE:25852', ['PROTEIN:10157']),
  ('GENE:33538', ['PROTEIN:20506']),
  ('GENE:25983', ['PROTEIN:2647']),
  ('GENE:25983', ['PROTEIN:2647']),
  ('GENE:26817', ['PROTEIN:4058']),
  ('GENE:34988', ['PROTEIN:19533']),
  ('GENE:26556', ['PROTEIN:1337']),
  ('GENE:25858', ['PROTEIN:11585']),
  ('GENE:30275', ['PROTEIN:9169']),
  ('GENE:24666', ['PROTEIN:10853'])],
 '2871': [('GENE:28214', ['PROTEIN:1556']),
  ('GENE:28215', ['PROTEIN:13325']),
  ('GENE:28218', ['PROTEIN:1157']),
  ('GENE:28214', ['PROTEIN:1556']),
  ('GENE:28215', ['PROTEIN:13325']),
  ('GENE:28218', ['PROTEIN:1157']),
  ('GENE:27254', ['PROTEIN:12114']),
  ('GENE:27254', ['PROTEIN:12114']),
  ('GENE:31001', ['PROTEIN:1265']),
  ('GENE:29300', ['PROTEIN:100']),
  ('GENE:29300', ['PROTEIN:100']),
  ('GENE:29316', ['PROTEIN:99'])],
 '28244': [('GENE:28626', ['PROTEIN:1453']),
  ('GENE:28626', ['PROTEIN:1453']),
  ('GENE:28626', ['PROTEIN:1453']),
  ('GENE:28626', ['PROTEIN:1453']),
  ('GENE:28626', ['PROTEIN:1453'])],
 '2662': [('GENE:33126', ['PROTEIN:8513']), ('GENE:33126', ['PROTEIN:8513'])],
 '75981': [('GENE:32620', ['PROTEIN:6233']),
  ('GENE:32620', ['PROTEIN:6233']),
  ('GENE:27686', ['PROTEIN:13605']),

In [31]:
import pickle

In [32]:
pickle.dump(diseases_reasons, open(os.path.join(project_name, "diseases_reasons.pickle"), "wb"))

In [33]:
for item, _ in zip(diseases_reasons.items(), range(10)):
    print(item)
print('...')

('75839', [('GENE:27214', ['PROTEIN:6548']), ('GENE:32979', ['PROTEIN:12455']), ('GENE:33448', ['PROTEIN:21970']), ('GENE:26178', ['PROTEIN:2126']), ('GENE:29712', ['PROTEIN:19712']), ('GENE:33530', ['PROTEIN:6141']), ('GENE:33531', ['PROTEIN:16612']), ('GENE:25133', ['PROTEIN:11602']), ('GENE:31252', ['PROTEIN:10825']), ('GENE:25090', ['PROTEIN:10887']), ('GENE:25090', ['PROTEIN:10887']), ('GENE:35649', ['PROTEIN:1742']), ('GENE:35649', ['PROTEIN:1742']), ('GENE:26843', ['PROTEIN:10307']), ('GENE:30694', ['PROTEIN:15222']), ('GENE:25464', ['PROTEIN:271']), ('GENE:25464', ['PROTEIN:271']), ('GENE:28937', ['PROTEIN:82']), ('GENE:31669', ['PROTEIN:6051']), ('GENE:32797', ['PROTEIN:12522']), ('GENE:34633', ['PROTEIN:11934']), ('GENE:25030', ['PROTEIN:18347']), ('GENE:27163', ['PROTEIN:12055']), ('GENE:32600', ['PROTEIN:16803']), ('GENE:27301', ['PROTEIN:18552']), ('GENE:27301', ['PROTEIN:18552']), ('GENE:28019', ['PROTEIN:14633']), ('GENE:28022', ['PROTEIN:8647']), ('GENE:33383', ['PROTEIN:1244']), ('GENE:34134', ['PROTEIN:15102']), ('GENE:25703', ['PROTEIN:15101']), ('GENE:32386', ['PROTEIN:1284']), ('GENE:26006', ['PROTEIN:7164']), ('GENE:28276', ['PROTEIN:11933']), ('GENE:31945', ['PROTEIN:21541']), ('GENE:25568', ['PROTEIN:20857']), ('GENE:26382', ['PROTEIN:18662']), ('GENE:25568', ['PROTEIN:20857']), ('GENE:26382', ['PROTEIN:18662']), ('GENE:27753', ['PROTEIN:17030']), ('GENE:31293', ['PROTEIN:6112']), ('GENE:32839', ['PROTEIN:20246']), ('GENE:33875', ['PROTEIN:17670']), ('GENE:32242', ['PROTEIN:6587']), ('GENE:27301', ['PROTEIN:18552']), ('GENE:28341', ['PROTEIN:17439']), ('GENE:27866', ['PROTEIN:10367']), ('GENE:31997', ['PROTEIN:11412']), ('GENE:34836', ['PROTEIN:6273']), ('GENE:34836', ['PROTEIN:6273']), ('GENE:27110', ['PROTEIN:11776']), ('GENE:27762', ['PROTEIN:8012']), ('GENE:27762', ['PROTEIN:8012']), ('GENE:32806', ['PROTEIN:14463']), ('GENE:33176', ['PROTEIN:16344']), ('GENE:31852', ['PROTEIN:18063']), ('GENE:26613', ['PROTEIN:4025']), ('GENE:31611', ['PROTEIN:10620']), ('GENE:29908', ['PROTEIN:15020']), ('GENE:28867', ['PROTEIN:18013']), ('GENE:28276', ['PROTEIN:11933']), ('GENE:28863', ['PROTEIN:4446']), ('GENE:26568', ['PROTEIN:2419']), ('GENE:30267', ['PROTEIN:21327']), ('GENE:33448', ['PROTEIN:21970']), ('GENE:32979', ['PROTEIN:12455']), ('GENE:33448', ['PROTEIN:21970']), ('GENE:31931', ['PROTEIN:8454']), ('GENE:27072', ['PROTEIN:9396']), ('GENE:33095', ['PROTEIN:21783']), ('GENE:33688', ['PROTEIN:6158']), ('GENE:31923', ['PROTEIN:12355']), ('GENE:34069', ['PROTEIN:8881']), ('GENE:27444', ['PROTEIN:21238']), ('GENE:33448', ['PROTEIN:21970']), ('GENE:30381', ['PROTEIN:20064']), ('GENE:33448', ['PROTEIN:21970'])])
('2725', [('GENE:30136', ['PROTEIN:1576']), ('GENE:30136', ['PROTEIN:1576']), ('GENE:26633', ['PROTEIN:710']), ('GENE:28943', ['PROTEIN:1754']), ('GENE:26633', ['PROTEIN:710']), ('GENE:26633', ['PROTEIN:710']), ('GENE:30605', ['PROTEIN:3536']), ('GENE:30605', ['PROTEIN:3536']), ('GENE:29696', ['PROTEIN:21188']), ('GENE:29696', ['PROTEIN:21188']), ('GENE:29696', ['PROTEIN:21188'])])
('7564', [('GENE:27045', ['PROTEIN:3759']), ('GENE:27045', ['PROTEIN:3759']), ('GENE:31092', ['PROTEIN:13998']), ('GENE:32264', ['PROTEIN:4311']), ('GENE:32264', ['PROTEIN:4311']), ('GENE:30332', ['PROTEIN:1820']), ('GENE:30332', ['PROTEIN:1820']), ('GENE:26951', ['PROTEIN:8766']), ('GENE:26951', ['PROTEIN:8766']), ('GENE:29811', ['PROTEIN:10596']), ('GENE:25808', ['PROTEIN:93']), ('GENE:25808', ['PROTEIN:93']), ('GENE:25808', ['PROTEIN:93']), ('GENE:29054', ['PROTEIN:1917']), ('GENE:29056', ['PROTEIN:1916']), ('GENE:31981', ['PROTEIN:3771']), ('GENE:27229', ['PROTEIN:10969']), ('GENE:29271', ['PROTEIN:6143']), ('GENE:27229', ['PROTEIN:10969']), ('GENE:25874', ['PROTEIN:1690']), ('GENE:25874', ['PROTEIN:1690']), ('GENE:25808', ['PROTEIN:93']), ('GENE:25808', ['PROTEIN:93']), ('GENE:31077', ['PROTEIN:10852']), ('GENE:26595', ['PROTEIN:18534']), ('GENE:26595', ['PROTEIN:18534']), ('GENE:25808', ['PROTEIN:93']), ('GENE:26595', ['PROTEIN:18534']), ('GENE:26595', ['PROTEIN:18534']), ('GENE:35336', ['PROTEIN:9776']), ('GENE:35336', ['PROTEIN:9776']), ('GENE:32264', ['PROTEIN:4311']), ('GENE:32264', ['PROTEIN:4311']), ('GENE:25808', ['PROTEIN:93']), ('GENE:27317', ['PROTEIN:1778']), ('GENE:25808', ['PROTEIN:93']), ('GENE:27317', ['PROTEIN:1778']), ('GENE:28372', ['PROTEIN:460']), ('GENE:28372', ['PROTEIN:460']), ('GENE:25808', ['PROTEIN:93']), ('GENE:25808', ['PROTEIN:93']), ('GENE:29475', ['PROTEIN:21167']), ('GENE:29475', ['PROTEIN:21167']), ('GENE:27045', ['PROTEIN:3759']), ('GENE:27045', ['PROTEIN:3759']), ('GENE:27222', ['PROTEIN:4443']), ('GENE:27222', ['PROTEIN:4443']), ('GENE:29054', ['PROTEIN:1917']), ('GENE:29056', ['PROTEIN:1916']), ('GENE:26595', ['PROTEIN:18534']), ('GENE:26595', ['PROTEIN:18534']), ('GENE:26541', ['PROTEIN:2394']), ('GENE:26541', ['PROTEIN:2394']), ('GENE:29868', ['PROTEIN:12032']), ('GENE:29868', ['PROTEIN:12032']), ('GENE:27045', ['PROTEIN:3759']), ('GENE:27045', ['PROTEIN:3759']), ('GENE:25858', ['PROTEIN:11585']), ('GENE:25860', ['PROTEIN:20808']), ('GENE:32101', ['PROTEIN:2757']), ('GENE:32101', ['PROTEIN:2757']), ('GENE:29797', ['PROTEIN:18143']), ('GENE:28884', ['PROTEIN:20643']), ('GENE:29797', ['PROTEIN:18143']), ('GENE:32119', ['PROTEIN:16629']), ('GENE:30551', ['PROTEIN:20376']), ('GENE:31077', ['PROTEIN:10852']), ('GENE:35107', ['PROTEIN:16714']), ('GENE:26541', ['PROTEIN:2394']), ('GENE:26541', ['PROTEIN:2394']), ('GENE:27045', ['PROTEIN:3759']), ('GENE:27045', ['PROTEIN:3759']), ('GENE:32526', ['PROTEIN:19988']), ('GENE:25808', ['PROTEIN:93']), ('GENE:25808', ['PROTEIN:93']), ('GENE:29970', ['PROTEIN:1389']), ('GENE:29970', ['PROTEIN:1389']), ('GENE:32933', ['PROTEIN:16083']), ('GENE:32933', ['PROTEIN:16083']), ('GENE:25808', ['PROTEIN:93']), ('GENE:30684', ['PROTEIN:274']), ('GENE:30684', ['PROTEIN:274']), ('GENE:25808', ['PROTEIN:93']), ('GENE:25808', ['PROTEIN:93']), ('GENE:27045', ['PROTEIN:3759']), ('GENE:27045', ['PROTEIN:3759']), ('GENE:30359', ['PROTEIN:1288']), ('GENE:25860', ['PROTEIN:20808']), ('GENE:28937', ['PROTEIN:82']), ('GENE:32603', ['PROTEIN:9758', 'PROTEIN:9759']), ('GENE:25808', ['PROTEIN:93'])])
('7560', [('GENE:27047', ['PROTEIN:80']), ('GENE:27047', ['PROTEIN:80']), ('GENE:32444', ['PROTEIN:1499']), ('GENE:32444', ['PROTEIN:1499']), ('GENE:25235', ['PROTEIN:8004']), ('GENE:32296', ['PROTEIN:18467']), ('GENE:27213', ['PROTEIN:10845']), ('GENE:25808', ['PROTEIN:93']), ('GENE:25860', ['PROTEIN:20808']), ('GENE:27044', ['PROTEIN:81']), ('GENE:27047', ['PROTEIN:80']), ('GENE:24790', ['PROTEIN:18565']), ('GENE:24790', ['PROTEIN:18565']), ('GENE:30167', ['PROTEIN:12099']), ('GENE:30167', ['PROTEIN:12099']), ('GENE:27729', ['PROTEIN:19817']), ('GENE:25858', ['PROTEIN:11585']), ('GENE:25858', ['PROTEIN:11585']), ('GENE:30292', ['PROTEIN:12134']), ('GENE:30292', ['PROTEIN:12134']), ('GENE:27362', ['PROTEIN:13338']), ('GENE:25586', ['PROTEIN:11205']), ('GENE:25586', ['PROTEIN:11205']), ('GENE:30745', ['PROTEIN:351']), ('GENE:31582', ['PROTEIN:1977']), ('GENE:26838', ['PROTEIN:16198']), ('GENE:25900', ['PROTEIN:9022']), ('GENE:26838', ['PROTEIN:16198']), ('GENE:25900', ['PROTEIN:9022']), ('GENE:34731', ['PROTEIN:15177']), ('GENE:25586', ['PROTEIN:11205']), ('GENE:25586', ['PROTEIN:11205']), ('GENE:28179', ['PROTEIN:7393']), ('GENE:26638', ['PROTEIN:3832']), ('GENE:28179', ['PROTEIN:7393']), ('GENE:31006', ['PROTEIN:19998']), ('GENE:24790', ['PROTEIN:18565']), ('GENE:30494', ['PROTEIN:13753']), ('GENE:30494', ['PROTEIN:13753']), ('GENE:28152', ['PROTEIN:11814']), ('GENE:28152', ['PROTEIN:11814']), ('GENE:33490', ['PROTEIN:5974']), ('GENE:34061', ['PROTEIN:18080']), ('GENE:33490', ['PROTEIN:5974']), ('GENE:34061', ['PROTEIN:18080']), ('GENE:26323', ['PROTEIN:17839']), ('GENE:26323', ['PROTEIN:17839']), ('GENE:35034', ['PROTEIN:21971']), ('GENE:35034', ['PROTEIN:21971']), ('GENE:33174', ['PROTEIN:3291']), ('GENE:33174', ['PROTEIN:3291']), ('GENE:26951', ['PROTEIN:8766']), ('GENE:29810', ['PROTEIN:10595']), ('GENE:34156', ['PROTEIN:8471']), ('GENE:27045', ['PROTEIN:3759']), ('GENE:27045', ['PROTEIN:3759']), ('GENE:27222', ['PROTEIN:4443']), ('GENE:27222', ['PROTEIN:4443']), ('GENE:35507', ['PROTEIN:15366']), ('GENE:30574', ['PROTEIN:12442', 'PROTEIN:15368']), ('GENE:34408', ['PROTEIN:21625']), ('GENE:27047', ['PROTEIN:80']), ('GENE:33404', ['PROTEIN:11204']), ('GENE:27045', ['PROTEIN:3759']), ('GENE:27047', ['PROTEIN:80']), ('GENE:33404', ['PROTEIN:11204']), ('GENE:27047', ['PROTEIN:80']), ('GENE:27047', ['PROTEIN:80']), ('GENE:26515', ['PROTEIN:1578']), ('GENE:26515', ['PROTEIN:1578']), ('GENE:32994', ['PROTEIN:14023']), ('GENE:24671', ['PROTEIN:7031']), ('GENE:28869', ['PROTEIN:11868']), ('GENE:27021', ['PROTEIN:7401']), ('GENE:27021', ['PROTEIN:7401']), ('GENE:27814', ['PROTEIN:21829']), ('GENE:27814', ['PROTEIN:21829']), ('GENE:34558', ['PROTEIN:13683']), ('GENE:34558', ['PROTEIN:13683']), ('GENE:26847', ['PROTEIN:11739']), ('GENE:27129', ['PROTEIN:10890']), ('GENE:27129', ['PROTEIN:10890']), ('GENE:27130', ['PROTEIN:9409']), ('GENE:27655', ['PROTEIN:16880']), ('GENE:25827', ['PROTEIN:12624']), ('GENE:27044', ['PROTEIN:81']), ('GENE:32309', ['PROTEIN:3444']), ('GENE:33274', ['PROTEIN:4328']), ('GENE:30056', ['PROTEIN:323']), ('GENE:30862', ['PROTEIN:21557']), ('GENE:30862', ['PROTEIN:21557']), ('GENE:30067', ['PROTEIN:15054']), ('GENE:30067', ['PROTEIN:15054']), ('GENE:35355', ['PROTEIN:17238']), ('GENE:35355', ['PROTEIN:17238']), ('GENE:27045', ['PROTEIN:3759']), ('GENE:33182', ['PROTEIN:18016']), ('GENE:33404', ['PROTEIN:11204']), ('GENE:26816', ['PROTEIN:14722']), ('GENE:33404', ['PROTEIN:11204']), ('GENE:24934', ['PROTEIN:21667']), ('GENE:24934', ['PROTEIN:21667']), ('GENE:27045', ['PROTEIN:3759']), ('GENE:27045', ['PROTEIN:3759']), ('GENE:27222', ['PROTEIN:4443']), ('GENE:26816', ['PROTEIN:14722']), ('GENE:27047', ['PROTEIN:80']), ('GENE:29799', ['PROTEIN:18144']), ('GENE:32948', ['PROTEIN:1551']), ('GENE:30501', ['PROTEIN:575']), ('GENE:32444', ['PROTEIN:1499']), ('GENE:31561', ['PROTEIN:9284']), ('GENE:33755', ['PROTEIN:14115']), ('GENE:32393', ['PROTEIN:4450']), ('GENE:27540', ['PROTEIN:1059']), ('GENE:31379', ['PROTEIN:2599']), ('GENE:28043', ['PROTEIN:10349']), ('GENE:25316', ['PROTEIN:9000']), ('GENE:28501', ['PROTEIN:17155']), ('GENE:27775', ['PROTEIN:19117']), ('GENE:32200', ['PROTEIN:1521']), ('GENE:24803', ['PROTEIN:15504']), ('GENE:33136', ['PROTEIN:8115']), ('GENE:26847', ['PROTEIN:11739']), ('GENE:27047', ['PROTEIN:80']), ('GENE:27047', ['PROTEIN:80']), ('GENE:27044', ['PROTEIN:81']), ('GENE:27047', ['PROTEIN:80']), ('GENE:25267', ['PROTEIN:15987'])])
('2530', [('GENE:35094', ['PROTEIN:14369']), ('GENE:29916', ['PROTEIN:6167']), ('GENE:35094', ['PROTEIN:14369'])])
('75169', [('GENE:26580', ['PROTEIN:19607'])])
('28243', [('GENE:28624', ['PROTEIN:1454']), ('GENE:28625', ['PROTEIN:1454']), ('GENE:28626', ['PROTEIN:1453']), ('GENE:28624', ['PROTEIN:1454']), ('GENE:28625', ['PROTEIN:1454']), ('GENE:31188', ['PROTEIN:20667']), ('GENE:31188', ['PROTEIN:20667']), ('GENE:28624', ['PROTEIN:1454']), ('GENE:28625', ['PROTEIN:1454']), ('GENE:28624', ['PROTEIN:1454']), ('GENE:28625', ['PROTEIN:1454'])])
('74722', [('GENE:26735', ['PROTEIN:1202']), ('GENE:26735', ['PROTEIN:1202'])])
('2727', [('GENE:26534', ['PROTEIN:19065']), ('GENE:26534', ['PROTEIN:19065']), ('GENE:29853', ['PROTEIN:6170']), ('GENE:29852', ['PROTEIN:6166']), ('GENE:27554', ['PROTEIN:6173']), ('GENE:27554', ['PROTEIN:6173']), ('GENE:31222', ['PROTEIN:6428']), ('GENE:31222', ['PROTEIN:6428']), ('GENE:24587', ['PROTEIN:11812']), ('GENE:24587', ['PROTEIN:11812']), ('GENE:27920', ['PROTEIN:6647']), ('GENE:30258', ['PROTEIN:825']), ('GENE:33813', ['PROTEIN:13815']), ('GENE:34925', ['PROTEIN:3546']), ('GENE:35227', ['PROTEIN:20090']), ('GENE:35227', ['PROTEIN:20090']), ('GENE:35389', ['PROTEIN:16026']), ('GENE:35389', ['PROTEIN:16026']), ('GENE:31111', ['PROTEIN:19322']), ('GENE:31111', ['PROTEIN:19322']), ('GENE:24981', ['PROTEIN:7966']), ('GENE:24981', ['PROTEIN:7966']), ('GENE:33813', ['PROTEIN:13815']), ('GENE:27080', ['PROTEIN:19317']), ('GENE:27080', ['PROTEIN:19317']), ('GENE:35235', ['PROTEIN:20810']), ('GENE:35235', ['PROTEIN:20810']), ('GENE:27986', ['PROTEIN:379']), ('GENE:27986', ['PROTEIN:379']), ('GENE:33677', ['PROTEIN:15037']), ('GENE:33677', ['PROTEIN:15037']), ('GENE:29927', ['PROTEIN:15025']), ('GENE:29927', ['PROTEIN:15025']), ('GENE:33866', ['PROTEIN:20630']), ('GENE:33866', ['PROTEIN:20630']), ('GENE:31709', ['PROTEIN:9970']), ('GENE:31709', ['PROTEIN:9970']), ('GENE:34664', ['PROTEIN:9971']), ('GENE:34664', ['PROTEIN:9971']), ('GENE:33713', ['PROTEIN:20629']), ('GENE:33713', ['PROTEIN:20629']), ('GENE:33723', ['PROTEIN:6920']), ('GENE:33723', ['PROTEIN:6920']), ('GENE:35499', ['PROTEIN:18209']), ('GENE:35499', ['PROTEIN:18209']), ('GENE:34857', ['PROTEIN:17796']), ('GENE:34857', ['PROTEIN:17796']), ('GENE:24745', ['PROTEIN:17431']), ('GENE:24745', ['PROTEIN:17431']), ('GENE:28555', ['PROTEIN:14372']), ('GENE:28555', ['PROTEIN:14372']), ('GENE:29987', ['PROTEIN:6072']), ('GENE:29987', ['PROTEIN:6072']), ('GENE:31052', ['PROTEIN:18390']), ('GENE:31052', ['PROTEIN:18390']), ('GENE:26562', ['PROTEIN:6831']), ('GENE:26562', ['PROTEIN:6831']), ('GENE:34457', ['PROTEIN:20811']), ('GENE:34457', ['PROTEIN:20811']), ('GENE:27688', ['PROTEIN:7145']), ('GENE:24921', ['PROTEIN:17686']), ('GENE:30018', ['PROTEIN:17430']), ('GENE:34861', ['PROTEIN:19321']), ('GENE:33889', ['PROTEIN:6921']), ('GENE:29327', ['PROTEIN:12598']), ('GENE:33058', ['PROTEIN:11087']), ('GENE:32630', ['PROTEIN:17307']), ('GENE:33459', ['PROTEIN:7967']), ('GENE:29852', ['PROTEIN:6166']), ('GENE:29852', ['PROTEIN:6166']), ('GENE:26445', ['PROTEIN:10782']), ('GENE:26843', ['PROTEIN:10307']), ('GENE:32625', ['PROTEIN:9518']), ('GENE:31607', ['PROTEIN:6775']), ('GENE:25386', ['PROTEIN:2158']), ('GENE:27056', ['PROTEIN:16027']), ('GENE:30939', ['PROTEIN:6906']), ('GENE:31252', ['PROTEIN:10825']), ('GENE:30258', ['PROTEIN:825']), ('GENE:30258', ['PROTEIN:825'])])
('3348', [('GENE:30238', ['PROTEIN:842']), ('GENE:33515', ['PROTEIN:2838']), ('GENE:30884', ['PROTEIN:15875']), ('GENE:25733', ['PROTEIN:20498']), ('GENE:29129', ['PROTEIN:3787']), ('GENE:27042', ['PROTEIN:10338']), ('GENE:26583', ['PROTEIN:6977']), ('GENE:26583', ['PROTEIN:6977']), ('GENE:25182', ['PROTEIN:21496']), ('GENE:25182', ['PROTEIN:21496']), ('GENE:31145', ['PROTEIN:13914']), ('GENE:25182', ['PROTEIN:21496']), ('GENE:31145', ['PROTEIN:13914']), ('GENE:29995', ['PROTEIN:12069']), ('GENE:29995', ['PROTEIN:12069']), ('GENE:29945', ['PROTEIN:17510']), ('GENE:29945', ['PROTEIN:17510']), ('GENE:29945', ['PROTEIN:17510']), ('GENE:32819', ['PROTEIN:397']), ('GENE:32819', ['PROTEIN:397']), ('GENE:33680', ['PROTEIN:1103']), ('GENE:33680', ['PROTEIN:1103']), ('GENE:32516', ['PROTEIN:17511']), ('GENE:32516', ['PROTEIN:17511']), ('GENE:33165', ['PROTEIN:11133']), ('GENE:33165', ['PROTEIN:11133']), ('GENE:26114', ['PROTEIN:6714']), ('GENE:26114', ['PROTEIN:6714']), ('GENE:29945', ['PROTEIN:17510']), ('GENE:30906', ['PROTEIN:7810']), ('GENE:24961', ['PROTEIN:7723']), ('GENE:26360', ['PROTEIN:10220']), ('GENE:32078', ['PROTEIN:6183']), ('GENE:30594', ['PROTEIN:985']), ('GENE:32340', ['PROTEIN:362']), ('GENE:30020', ['PROTEIN:20873'])])
...

In [34]:
lens = [len(v) for v in diseases_reasons.values()]
print("avg:", sum(lens)/len(lens))
print("min:", min(lens))
print("max:", max(lens))

avg: 11.15891472868217
min: 1
max: 157

In [35]:
genes = []
proteins = []
for genes_proteins in diseases_reasons.values():
    for gene, protein in genes_proteins:
        genes.append(gene)
        proteins.extend(protein)
genes = set(genes)
proteins = set(proteins)
print("genes:", len(genes))
print("proteins:", len(proteins))

genes: 1512
proteins: 1517

In [36]:
df_phenotypes_valid = df_phenotypes[df_phenotypes['ICD-10'].notna()][['id', 'ICD-10']]

In [37]:
print(len(df_phenotypes_valid['ICD-10'].unique()))
df_phenotypes_valid.head()

29

                  id                     ICD-10
957    PHENOTYPE:958  R40.2 "Coma, unspecified"
1183  PHENOTYPE:1184                      Q21.1
1187  PHENOTYPE:1188                      Q21.3
1202  PHENOTYPE:1203                      Q24.0
1205  PHENOTYPE:1206                      Q21.1

In [38]:
diseases_reasons = pickle.load(open(os.path.join(project_name, "diseases_reasons.pickle"), "rb"))
_diseases_reasons = {}
for k, v in diseases_reasons.items():
    proteins = [protein for _, proteins in v for protein in proteins]
    _diseases_reasons[k] = proteins
pickle.dump(_diseases_reasons, open(os.path.join(project_name, "diseases_proteins_reasons.pickle"), "wb"))

In [39]:
lens = [len(v) for v in _diseases_reasons.values()]
print("avg:", sum(lens)/len(lens))
print("min:", min(lens))
print("max:", max(lens))

avg: 11.2984496124031
min: 1
max: 157

In [40]:
import json
json.dump(_diseases_reasons, open(os.path.join(project_name, "diseases_proteins_reasons.json"), "w"))

In [41]:
len(mimic_icd9)

6985

In [42]:
len(_diseases_reasons)

258

### Convert the relevant ICD-9 codes into textual descriptions.

In [43]:
from icd9_to_text import get_description

In [44]:
icd9_desc = []
for key in _diseases_reasons.keys():
    description = get_description(key)
    print(f"ICD9: {key}, Description: {description}")
    icd9_desc.append((key, description))
# save to csv
import pandas as pd
df = pd.DataFrame(icd9_desc, columns=['ICD9', 'Description'])
df.to_csv(f"{project_name}/icd9_desc.csv", index=False)

ICD9: 75839, Description: Autosomal deletions NEC
ICD9: 2725, Description: Lipoprotein deficiencies
ICD9: 7564, Description: Chondrodystrophy
ICD9: 7560, Description: Anomal skull/face bones
ICD9: 2530, Description: Acromegaly and gigantism
ICD9: 75169, Description: Biliary & liver anom NEC
ICD9: 28243, Description: Alpha thalassemia
ICD9: 74722, Description: Aortic atresia/stenosis
ICD9: 2727, Description: Lipidoses
ICD9: 3348, Description: Spinocerebellar dis NEC
ICD9: 75989, Description: Specfied cong anomal NEC
ICD9: 2871, Description: Thrombocytopathy
ICD9: 28244, Description: Beta thalassemia
ICD9: 2662, Description: B-complex defic NEC
ICD9: 75981, Description: Prader-willi syndrome
ICD9: 42789, Description: Cardiac dysrhythmias NEC
ICD9: 4530, Description: Budd-chiari syndrome
ICD9: 1123, Description: Cutaneous candidiasis
ICD9: 35989, Description: Myopathies NEC
ICD9: 75559, Description: Upper limb anomaly NEC
ICD9: 2370, Description: Unc behav neo pituitary
ICD9: 5811, Description: Epimembranous nephritis
ICD9: 5881, Description: Nephrogen diabetes insip
ICD9: 2774, Description: Dis bilirubin excretion
ICD9: 7428, Description: Nervous system anom NEC
ICD9: 75739, Description: Skin anomaly NEC
ICD9: 2821, Description: Heredit elliptocytosis
ICD9: 58389, Description: Nephritis NEC
ICD9: 27731, Description: Fam Mediterranean fever
ICD9: 3343, Description: Cerebellar ataxia NEC
ICD9: 2113, Description: Benign neoplasm lg bowel
ICD9: 1599, Description: Mal neo GI tract ill-def
ICD9: 4465, Description: Giant cell arteritis
ICD9: 2881, Description: Function dis neutrophils
ICD9: 7596, Description: Hamartoses NEC
ICD9: 2860, Description: Cong factor viii diord
ICD9: 2861, Description: Cong factor IX disorder
ICD9: 7513, Description: Hirschsprung's disease
ICD9: 3334, Description: Huntington's chorea
ICD9: 7422, Description: Reduction deform, brain
ICD9: 2722, Description: Mixed hyperlipidemia
ICD9: 3593, Description: Periodic paralysis
ICD9: 7467, Description: Hypoplas left heart synd
ICD9: 7571, Description: Ichthyosis congenita
ICD9: 75733, Description: Cong skin pigment anomal
ICD9: 74781, Description: Cerebrovascular anomaly
ICD9: 3590, Description: Cong hered musc dystrphy
ICD9: 2388, Description: Uncert behavior neo NEC
ICD9: 75317, Description: Medullary sponge kidney
ICD9: 1916, Description: Mal neo cerebellum NOS
ICD9: 7570, Description: Hereditary edema of legs
ICD9: 2252, Description: Ben neo cerebr meninges
ICD9: 1639, Description: Malig neopl pleura NOS
ICD9: 4375, Description: Moyamoya disease
ICD9: 7062, Description: Sebaceous cyst
ICD9: 3591, Description: Hered prog musc dystrphy
ICD9: 2706, Description: Dis urea cycle metabol
ICD9: 99799, Description: Surg compl-body syst NEC
ICD9: 3568, Description: Idio periph neurpthy NEC
ICD9: 3330, Description: Degen basal ganglia NEC
ICD9: 2832, Description: Hemolytic hemoglobinuria
ICD9: 6945, Description: Pemphigoid
ICD9: 2384, Description: Polycythemia vera
ICD9: 2598, Description: Endocrine disorders NEC
ICD9: 2273, Description: Benign neo pituitary
ICD9: 27549, Description: Dis calcium metablsm NEC
ICD9: 3379, Description: Autonomic nerve dis NEC
ICD9: 2718, Description: Dis carbohydr metab NEC
ICD9: 3308, Description: Cereb degen in child NEC
ICD9: 75732, Description: Vascular hamartomas
ICD9: 7424, Description: Brain anomaly NEC
ICD9: 69513, Description: Stevens-Johnson syndrome
ICD9: 69589, Description: Erythematous cond NEC
ICD9: 4467, Description: Takayasu's disease
ICD9: 7452, Description: Tetralogy of fallot
ICD9: 23871, Description: Essntial thrombocythemia
ICD9: 7595, Description: Tuberous sclerosis
ICD9: 2733, Description: Macroglobulinemia
ICD9: 2728, Description: Lipoid metabol dis NEC
ICD9: 2864, Description: Von willebrand's disease
ICD9: 27911, Description: Digeorge's syndrome
ICD9: 7563, Description: Rib & sternum anomal NEC
ICD9: 5300, Description: Achalasia & cardiospasm
ICD9: 74769, Description: Oth spcf prph vscl anoml
ICD9: 75489, Description: Nonteratogenic anom NEC
ICD9: 3562, Description: Hered sensory neuropathy
ICD9: 7566, Description: Anomalies of diaphragm
ICD9: 75671, Description: Prune belly syndrome
ICD9: 3341, Description: Hered spastic paraplegia
ICD9: 71120, Description: Behcet arthritis-unspec
ICD9: 2535, Description: Diabetes insipidus
ICD9: 3708, Description: Keratitis NEC
ICD9: 2720, Description: Pure hypercholesterolem
ICD9: 2822, Description: Glutathione dis anemia
ICD9: 5761, Description: Cholangitis
ICD9: 40591, Description: Renovasc hypertension
ICD9: 75881, Description: Oth cond due to sex chrm
ICD9: 75289, Description: Genital organ anom NEC
ICD9: 75889, Description: Oth con d/t chrm anm NEC
ICD9: 7569, Description: Musculoskel anom NEC/NOS
ICD9: 4254, Description: Prim cardiomyopathy NEC
ICD9: 33511, Description: Kugelberg-welander dis
ICD9: 75651, Description: Osteogenesis imperfecta
ICD9: 72889, Description: Muscle/ligament dis NEC
ICD9: 7575, Description: Nail anomalies NEC
ICD9: 2702, Description: Arom amin-acid metab NEC
ICD9: 7597, Description: Mult congen anomal NEC
ICD9: 2250, Description: Benign neoplasm brain
ICD9: 7018, Description: Skin hypertro/atroph NEC
ICD9: 7421, Description: Microcephalus
ICD9: 7530, Description: Renal agenesis
ICD9: 75162, Description: Cong cystic liver dis
ICD9: 74689, Description: Cong heart anomaly NEC
ICD9: 7333, Description: Hyperostosis of skull
ICD9: 75510, Description: Syndactyly, multiple/NOS
ICD9: 2594, Description: Dwarfism NEC
ICD9: 2820, Description: Hereditary spherocytosis
ICD9: 2707, Description: Straig amin-acid met NEC
ICD9: 23879, Description: Lymph/hematpoitc tis NEC
ICD9: 58189, Description: Nephrotic syndrome NEC
ICD9: 2552, Description: Adrenogenital disorders
ICD9: 2127, Description: Benign neoplasm heart
ICD9: 70909, Description: Other dyschromia
ICD9: 70409, Description: Alopecia NEC
ICD9: 2793, Description: Immunity deficiency NOS
ICD9: 75683, Description: Ehlers-danlos syndrome
ICD9: 3336, Description: Genetic torsion dystonia
ICD9: 7042, Description: Abnormalities of hair
ICD9: 2538, Description: Pituitary disorder NEC
ICD9: 6929, Description: Dermatitis NOS
ICD9: 74789, Description: Circulatory anomaly NEC
ICD9: 74405, Description: Anomalies of inner ear
ICD9: 6954, Description: Lupus erythematosus
ICD9: 59001, Description: Chr pyeloneph w med necr
ICD9: 2771, Description: Dis porphyrin metabolism
ICD9: 1589, Description: Mal neo peritoneum NOS
ICD9: 74423, Description: Microtia
ICD9: 74569, Description: Endocard cushion def NEC
ICD9: 7455, Description: Secundum atrial sept def
ICD9: 193, Description: Malignant neoplasm of thyroid gland
ICD9: 3342, Description: Primary cerebellar degen
ICD9: 2798, Description: Immune mechanism dis NEC
ICD9: 25201, Description: Primary hyperparathyroid
ICD9: 56489, Description: Funct dis intestine NEC
ICD9: 4480, Description: Heredit hemorr telangiec
ICD9: 2884, Description: Hemophagocytic syndromes
ICD9: 2572, Description: Testicular hypofunc NEC
ICD9: 2169, Description: Benign neoplasm skin NOS
ICD9: 7488, Description: Respiratory anomaly NEC
ICD9: 5716, Description: Biliary cirrhosis
ICD9: 75617, Description: Spina bifida occulta
ICD9: 2863, Description: Cong def clot factor NEC
ICD9: 2726, Description: Lipodystrophy
ICD9: 2375, Description: Unc beh neo brain/spinal
ICD9: 7778, Description: Perinat GI sys dis NEC
ICD9: 7108, Description: Diff connect tis dis NEC
ICD9: 4160, Description: Prim pulm hypertension
ICD9: 2810, Description: Pernicious anemia
ICD9: 2827, Description: Hemoglobinopathies NEC
ICD9: 20030, Description: Margnl zone lym xtrndl
ICD9: 74361, Description: Congenital ptosis
ICD9: 27739, Description: Amyloidosis NEC
ICD9: 7458, Description: Septal closure anom NEC
ICD9: 7092, Description: Scar & fibrosis of skin
ICD9: 243, Description: Congenital hypothyroidism
ICD9: 20260, Description: Mlg mast unsp xtrndl org
ICD9: 2511, Description: Oth spcf hypoglycemia
ICD9: 38918, Description: Sensonrl hear loss,bilat
ICD9: 7423, Description: Congenital hydrocephalus
ICD9: 75310, Description: Cystic kidney diseas NOS
ICD9: 2823, Description: Enzyme defic anemia NEC
ICD9: 79099, Description: Oth nspcf finding blood
ICD9: 2828, Description: Hered hemolytic anem NEC
ICD9: 69018, Description: Sebrrheic dermatitis NEC
ICD9: 3310, Description: Alzheimer's disease
ICD9: 3320, Description: Paralysis agitans
ICD9: 75026, Description: Mouth anomaly NEC
ICD9: 27789, Description: Metabolism disorder NEC
ICD9: 2558, Description: Adrenal disorder NEC
ICD9: 5778, Description: Pancreatic disease NEC
ICD9: 4266, Description: Other heart block
ICD9: 6868, Description: Local skin infection NEC
ICD9: 5601, Description: Paralytic ileus
ICD9: 74489, Description: Cong face/neck anom NEC
ICD9: 3335, Description: Chorea NEC
ICD9: 2811, Description: B12 defic anemia NEC
ICD9: 5238, Description: Periodontal disease NEC
ICD9: 6961, Description: Other psoriasis
ICD9: 7515, Description: Intestinal anomaly NEC
ICD9: 3332, Description: Myoclonus
ICD9: 7533, Description: Kidney anomaly NEC
ICD9: 7098, Description: Skin disorders NEC
ICD9: 7542, Description: Cong postural deformity
ICD9: 7450, Description: Common truncus
ICD9: 4471, Description: Stricture of artery
ICD9: 2897, Description: Methemoglobinemia
ICD9: 2808, Description: Iron defic anemia NEC
ICD9: 7485, Description: Agenesis of lung
ICD9: 4271, Description: Parox ventric tachycard
ICD9: 2381, Description: Unc behav neo soft tissu
ICD9: 7101, Description: Systemic sclerosis
ICD9: 3301, Description: Cerebral lipidoses
ICD9: 33379, Description: Acq torsion dystonia NEC
ICD9: 2862, Description: Cong factor xi disorder
ICD9: 3518, Description: Facial nerve dis NEC
ICD9: 2812, Description: Folate-deficiency anemia
ICD9: 1919, Description: Malig neo brain NOS
ICD9: 1540, Description: Mal neo rectosigmoid jct
ICD9: 28989, Description: Blood diseases NEC
ICD9: 1519, Description: Malig neopl stomach NOS
ICD9: 2869, Description: Coagulat defect NEC/NOS
ICD9: 7761, Description: Neonatal thrombocytopen
ICD9: 1941, Description: Malig neo parathyroid
ICD9: 769, Description: Respiratory distress syndrome in newborn
ICD9: 7751, Description: Neonat diabetes mellitus
ICD9: 2165, Description: Benign neo skin trunk
ICD9: 7038, Description: Diseases of nail NEC
ICD9: 27800, Description: Obesity NOS
ICD9: 2581, Description: Comb endocr dysfunct NEC
ICD9: 2713, Description: Disaccharidase def/malab
ICD9: 75501, Description: Polydactyly, fingers
ICD9: 2867, Description: Acq coagul factor defic
ICD9: 2164, Description: Ben neo scalp/skin neck
ICD9: 2724, Description: Hyperlipidemia NEC/NOS
ICD9: 25541, Description: Glucocorticoid deficient
ICD9: 4466, Description: Thrombot microangiopathy
ICD9: 2536, Description: Neurohypophysis dis NEC
ICD9: 2858, Description: Anemia NEC
ICD9: 3588, Description: Myoneural disorders NEC
ICD9: 3570, Description: Ac infect polyneuritis
ICD9: 74900, Description: Cleft palate NOS
ICD9: 74902, Description: Unilat cleft palate-inc
ICD9: 75313, Description: Polycyst kid-autosom dom
ICD9: 2550, Description: Cushing's syndrome
ICD9: 7041, Description: Hirsutism
ICD9: 2411, Description: Nontox multinodul goiter
ICD9: 7905, Description: Abn serum enzy level NEC
ICD9: 7704, Description: Primary atelectasis
ICD9: 77589, Description: Neonat endo/met dis NEC
ICD9: 4373, Description: Nonrupt cerebral aneurym
ICD9: 3181, Description: Sev intellect disability
ICD9: 2521, Description: Hypoparathyroidism
ICD9: 7767, Description: Neonatal neutropenia
ICD9: 7464, Description: Cong aorta valv insuffic
ICD9: 3430, Description: Congenital diplegia
ICD9: 5699, Description: Intestinal disorder NOS
ICD9: 2531, Description: Ant pituit hyperfunc NEC
ICD9: 6970, Description: Lichen planus
ICD9: 7011, Description: Keratoderma, acquired
ICD9: 77989, Description: Perinatal condition NEC
ICD9: 3688, Description: Visual disturbances NEC
ICD9: 1550, Description: Mal neo liver, primary
ICD9: 4412, Description: Thoracic aortic aneurysm
ICD9: 71430, Description: Juv rheum arthritis NOS
ICD9: 75319, Description: Cystic kidney diseas NEC
ICD9: 2592, Description: Carcinoid syndrome
ICD9: 7913, Description: Myoglobinuria
ICD9: 5200, Description: Anodontia